/**
 * The manifest's labels in the seven languages beside English, keyed by the
 * English (see `labels.ts`). EVERY LANGUAGE HERE IS AN UNREVIEWED DRAFT until
 * a native speaker has read it; the release waits for that review.
 */
import type { Translation } from "./labels.ts";

// prettier-ignore
export const WORDS: Record<string, Translation> = {
  "14+ with an adult": {"de-DE": "Ab 14 mit Erwachsenen", "fr-FR": "Dès 14 ans, accompagné d'un adulte", "da-DK": "14+ med en voksen", "cs-CZ": "14+ s doprovodem dospělého", "ar-EG": "من 14 عاما مع مرافق بالغ", "zh-CN": "14岁以上，需成人陪同", "zh-TW": "14 歲以上須成人陪同"},
  "16+": {"de-DE": "Ab 16", "fr-FR": "Dès 16 ans", "da-DK": "16+", "cs-CZ": "16+", "ar-EG": "من 16 عاما", "zh-CN": "16岁以上", "zh-TW": "16 歲以上"},
  "18+": {"de-DE": "Ab 18", "fr-FR": "Dès 18 ans", "da-DK": "18+", "cs-CZ": "18+", "ar-EG": "من 18 عاما", "zh-CN": "18岁以上", "zh-TW": "18 歲以上"},
  "A choice": {"de-DE": "Auswahl", "fr-FR": "Un choix", "da-DK": "Et valg", "cs-CZ": "Volba", "ar-EG": "اختيار", "zh-CN": "选项", "zh-TW": "一個選項"},
  "A later email took its place": {"de-DE": "Durch spätere E-Mail ersetzt", "fr-FR": "Remplacé par un e-mail plus récent", "da-DK": "En senere mail erstattede den", "cs-CZ": "Nahradil ho pozdější e-mail", "ar-EG": "حلّت محله رسالة لاحقة", "zh-CN": "已被之后的邮件取代", "zh-TW": "已由較新的信件取代"},
  "A message about your show": {"de-DE": "Eine Nachricht zu deiner Show", "fr-FR": "Un message sur votre spectacle", "da-DK": "En besked om dit arrangement", "cs-CZ": "Zpráva k vaší akci", "ar-EG": "رسالة بخصوص حفلك", "zh-CN": "关于你的演出的消息", "zh-TW": "演出相關訊息"},
  "A refund request was approved": {"de-DE": "Erstattungsanfrage genehmigt", "fr-FR": "Demande de remboursement acceptée", "da-DK": "En anmodning om refusion blev godkendt", "cs-CZ": "Žádost o vrácení peněz byla schválena", "ar-EG": "تمت الموافقة على طلب استرداد", "zh-CN": "退款申请已通过", "zh-TW": "退款申請已核准"},
  "A ticket from a friend": {"de-DE": "Ein Ticket von Freunden", "fr-FR": "Un billet envoyé par un proche", "da-DK": "En billet fra en ven", "cs-CZ": "Vstupenka od kamaráda", "ar-EG": "تذكرة من صديق", "zh-CN": "朋友送你的票", "zh-TW": "朋友送你的票"},
  "A ticket in your name": {"de-DE": "Ein Ticket auf deinen Namen", "fr-FR": "Un billet à votre nom", "da-DK": "En billet i dit navn", "cs-CZ": "Vstupenka na vaše jméno", "ar-EG": "تذكرة باسمك", "zh-CN": "登记在你名下的票", "zh-TW": "登記在你名下的票"},
  "About": {"de-DE": "Info", "fr-FR": "À propos", "da-DK": "Om", "cs-CZ": "Informace", "ar-EG": "نبذة", "zh-CN": "关于", "zh-TW": "關於"},
  "Accept by": {"de-DE": "Annehmen bis", "fr-FR": "À accepter avant", "da-DK": "Acceptér senest", "cs-CZ": "Přijmout do", "ar-EG": "آخر موعد للقبول", "zh-CN": "接收截止", "zh-TW": "接受期限"},
  "Accepted": {"de-DE": "Angenommen", "fr-FR": "Accepté", "da-DK": "Accepteret", "cs-CZ": "Přijato", "ar-EG": "مقبولة", "zh-CN": "已接收", "zh-TW": "已接受"},
  "Access needs": {"de-DE": "Zugangsbedürfnisse", "fr-FR": "Besoins d'accessibilité", "da-DK": "Behov for tilgængelighed", "cs-CZ": "Zvláštní potřeby", "ar-EG": "احتياجات الوصول", "zh-CN": "无障碍需求", "zh-TW": "無障礙需求"},
  "Accessibility": {"de-DE": "Barrierefreiheit", "fr-FR": "Accessibilité", "da-DK": "Tilgængelighed", "cs-CZ": "Bezbariérovost", "ar-EG": "سهولة الوصول", "zh-CN": "无障碍", "zh-TW": "無障礙設施"},
  "Account name": {"de-DE": "Kontoinhaber", "fr-FR": "Titulaire du compte", "da-DK": "Kontonavn", "cs-CZ": "Název účtu", "ar-EG": "اسم الحساب", "zh-CN": "户名", "zh-TW": "戶名"},
  "Account number": {"de-DE": "Kontonummer", "fr-FR": "Numéro de compte", "da-DK": "Kontonummer", "cs-CZ": "Číslo účtu", "ar-EG": "رقم الحساب", "zh-CN": "账号", "zh-TW": "帳號"},
  "Act": {"de-DE": "Act", "fr-FR": "Artiste", "da-DK": "Kunstner", "cs-CZ": "Účinkující", "ar-EG": "الفنان", "zh-CN": "表演者", "zh-TW": "演出者"},
  "Acts": {"de-DE": "Acts", "fr-FR": "Artistes", "da-DK": "Kunstnere", "cs-CZ": "Účinkující", "ar-EG": "الفنانون", "zh-CN": "演出阵容", "zh-TW": "演出陣容"},
  "Added by": {"de-DE": "Hinzugefügt von", "fr-FR": "Ajouté par", "da-DK": "Tilføjet af", "cs-CZ": "Kdo přidal", "ar-EG": "أضافه", "zh-CN": "添加人", "zh-TW": "新增者"},
  "Address": {"de-DE": "Adresse", "fr-FR": "Adresse", "da-DK": "Adresse", "cs-CZ": "Adresa", "ar-EG": "العنوان", "zh-CN": "地址", "zh-TW": "地址"},
  "Age": {"de-DE": "Alter", "fr-FR": "Âge", "da-DK": "Alder", "cs-CZ": "Věk", "ar-EG": "العمر", "zh-CN": "年龄", "zh-TW": "年齡"},
  "Age for new shows": {"de-DE": "Alter für neue Shows", "fr-FR": "Âge par défaut des nouveaux spectacles", "da-DK": "Aldersgrænse for nye arrangementer", "cs-CZ": "Věk pro nové akce", "ar-EG": "العمر للحفلات الجديدة", "zh-CN": "新演出的年龄限制", "zh-TW": "新演出預設年齡限制"},
  "Age line": {"de-DE": "Altershinweis", "fr-FR": "Mention d'âge", "da-DK": "Tekst om alder", "cs-CZ": "Věková poznámka", "ar-EG": "سطر العمر", "zh-CN": "年龄说明", "zh-TW": "年齡說明"},
  "All ages": {"de-DE": "Ohne Altersgrenze", "fr-FR": "Tout public", "da-DK": "Alle aldre", "cs-CZ": "Bez věkového omezení", "ar-EG": "لكل الأعمار", "zh-CN": "不限年龄", "zh-TW": "不限年齡"},
  "Amount": {"de-DE": "Betrag", "fr-FR": "Montant", "da-DK": "Beløb", "cs-CZ": "Částka", "ar-EG": "المبلغ", "zh-CN": "金额", "zh-TW": "金額"},
  "Amount off": {"de-DE": "Rabatt als Betrag", "fr-FR": "Remise en montant", "da-DK": "Rabatbeløb", "cs-CZ": "Sleva částkou", "ar-EG": "مبلغ الخصم", "zh-CN": "减免金额", "zh-TW": "折抵金額"},
  "Announced": {"de-DE": "Angekündigt", "fr-FR": "Annoncé", "da-DK": "Offentliggjort", "cs-CZ": "Oznámeno", "ar-EG": "أُعلن عنه", "zh-CN": "已公布", "zh-TW": "已公布"},
  "Answer": {"de-DE": "Antwort", "fr-FR": "Réponse", "da-DK": "Svar", "cs-CZ": "Odpověď", "ar-EG": "الإجابة", "zh-CN": "回答", "zh-TW": "回答"},
  "Answers": {"de-DE": "Antworten", "fr-FR": "Réponses", "da-DK": "Svar", "cs-CZ": "Odpovědi", "ar-EG": "الإجابات", "zh-CN": "回答", "zh-TW": "所有回答"},
  "Arrived": {"de-DE": "Angekommen", "fr-FR": "Arrivé", "da-DK": "Ankommet", "cs-CZ": "Dorazilo", "ar-EG": "وصل", "zh-CN": "已到场", "zh-TW": "已到場"},
  "Asked": {"de-DE": "Gefragt", "fr-FR": "Demandé", "da-DK": "Anmodet", "cs-CZ": "Vyžádáno", "ar-EG": "طُلب", "zh-CN": "申请时间", "zh-TW": "提出時間"},
  "At least": {"de-DE": "Mindestens", "fr-FR": "Au moins", "da-DK": "Mindst", "cs-CZ": "Alespoň", "ar-EG": "على الأقل", "zh-CN": "至少", "zh-TW": "至少"},
  "At most in one order": {"de-DE": "Höchstens pro Bestellung", "fr-FR": "Maximum par commande", "da-DK": "Højst pr. ordre", "cs-CZ": "Nejvýše v jedné objednávce", "ar-EG": "الحد الأقصى في الطلب الواحد", "zh-CN": "每单最多", "zh-TW": "每筆訂單上限"},
  "At the box office": {"de-DE": "An der Kasse", "fr-FR": "À la billetterie", "da-DK": "I billetlugen", "cs-CZ": "V pokladně", "ar-EG": "في شباك التذاكر", "zh-CN": "在售票处", "zh-TW": "售票處"},
  "At the door": {"de-DE": "Am Einlass", "fr-FR": "À l'entrée", "da-DK": "Ved døren", "cs-CZ": "U vchodu", "ar-EG": "عند الباب", "zh-CN": "在门口", "zh-TW": "現場"},
  "Awaiting bank transfer": {"de-DE": "Warte auf Überweisung", "fr-FR": "En attente du virement bancaire", "da-DK": "Afventer bankoverførsel", "cs-CZ": "Čeká na bankovní převod", "ar-EG": "بانتظار التحويل البنكي", "zh-CN": "等待银行转账", "zh-TW": "等待銀行轉帳"},
  "Awaiting transfer": {"de-DE": "Überweisung ausstehend", "fr-FR": "Virement attendu", "da-DK": "Afventer overførsel", "cs-CZ": "Čeká na převod", "ar-EG": "بانتظار التحويل", "zh-CN": "等待转账", "zh-TW": "等待轉帳"},
  "Back for the waitlist": {"de-DE": "Zurück für die Warteliste", "fr-FR": "Remis à la liste d'attente", "da-DK": "Tilbage til ventelisten", "cs-CZ": "Vráceno pro čekací listinu", "ar-EG": "عادت لقائمة الانتظار", "zh-CN": "退给候补名单", "zh-TW": "釋回給候補名單"},
  "Back on sale": {"de-DE": "Wieder im Verkauf", "fr-FR": "Remis en vente", "da-DK": "Til salg igen", "cs-CZ": "Znovu v prodeji", "ar-EG": "عادت إلى البيع", "zh-CN": "重新开售", "zh-TW": "重新開賣"},
  "Back on sale at doors": {"de-DE": "Ab Einlass wieder im Verkauf", "fr-FR": "Remis en vente à l'ouverture des portes", "da-DK": "Til salg igen ved døren", "cs-CZ": "Znovu v prodeji u vchodu", "ar-EG": "تعود إلى البيع عند فتح الأبواب", "zh-CN": "开门时重新开售", "zh-TW": "現場重新開賣"},
  "Bags": {"de-DE": "Taschen", "fr-FR": "Sacs", "da-DK": "Tasker", "cs-CZ": "Tašky a batohy", "ar-EG": "الحقائب", "zh-CN": "包袋", "zh-TW": "隨身包包"},
  "Balcony": {"de-DE": "Balkon", "fr-FR": "Balcon", "da-DK": "Balkon", "cs-CZ": "Balkon", "ar-EG": "الشرفة", "zh-CN": "楼座", "zh-TW": "二樓看台"},
  "Bank": {"de-DE": "Bank", "fr-FR": "Banque", "da-DK": "Bank", "cs-CZ": "Banka", "ar-EG": "البنك", "zh-CN": "银行", "zh-TW": "銀行"},
  "Bank transfer": {"de-DE": "Überweisung", "fr-FR": "Virement bancaire", "da-DK": "Bankoverførsel", "cs-CZ": "Bankovní převod", "ar-EG": "تحويل بنكي", "zh-CN": "银行转账", "zh-TW": "銀行轉帳"},
  "Both rooms": {"de-DE": "Beide Räume", "fr-FR": "Les deux salles", "da-DK": "Begge sale", "cs-CZ": "Oba sály", "ar-EG": "القاعتان معا", "zh-CN": "两个厅", "zh-TW": "兩個廳"},
  "Box office only": {"de-DE": "Nur an der Kasse", "fr-FR": "Billetterie uniquement", "da-DK": "Kun i billetlugen", "cs-CZ": "Jen v pokladně", "ar-EG": "من شباك التذاكر فقط", "zh-CN": "仅限售票处", "zh-TW": "僅限售票處"},
  "Box-office note": {"de-DE": "Notiz der Kasse", "fr-FR": "Note de la billetterie", "da-DK": "Note fra billetlugen", "cs-CZ": "Poznámka pokladny", "ar-EG": "ملاحظة شباك التذاكر", "zh-CN": "售票处备注", "zh-TW": "售票處備註"},
  "Buyer": {"de-DE": "Käufer", "fr-FR": "Acheteur", "da-DK": "Køber", "cs-CZ": "Kupující", "ar-EG": "المشتري", "zh-CN": "购票人", "zh-TW": "購票人"},
  "By": {"de-DE": "Von", "fr-FR": "Par", "da-DK": "Af", "cs-CZ": "Kdo", "ar-EG": "بواسطة", "zh-CN": "操作人", "zh-TW": "經手人"},
  "Came back unaccepted": {"de-DE": "Nicht angenommen zurück", "fr-FR": "Revenu sans être accepté", "da-DK": "Kom tilbage uden at blive accepteret", "cs-CZ": "Vráceno nepřijaté", "ar-EG": "عادت دون قبول", "zh-CN": "未被接收，已退回", "zh-TW": "未獲接受而退回"},
  "Cancellation email": {"de-DE": "Absage-E-Mail", "fr-FR": "E-mail d'annulation", "da-DK": "Mail om aflysning", "cs-CZ": "E-mail o zrušení", "ar-EG": "رسالة الإلغاء", "zh-CN": "取消通知邮件", "zh-TW": "取消通知信"},
  "Cancelled": {"de-DE": "Storniert", "fr-FR": "Annulé", "da-DK": "Annulleret", "cs-CZ": "Zrušeno", "ar-EG": "ملغاة", "zh-CN": "已取消", "zh-TW": "已取消"},
  "Cancelled tickets": {"de-DE": "Stornierte Tickets", "fr-FR": "Billets annulés", "da-DK": "Annullerede billetter", "cs-CZ": "Zrušené vstupenky", "ar-EG": "التذاكر الملغاة", "zh-CN": "已取消的票", "zh-TW": "已取消的票"},
  "Capacity": {"de-DE": "Kapazität", "fr-FR": "Jauge", "da-DK": "Kapacitet", "cs-CZ": "Kapacita", "ar-EG": "السعة", "zh-CN": "容量", "zh-TW": "容納人數"},
  "Card": {"de-DE": "Karte", "fr-FR": "Carte", "da-DK": "Kort", "cs-CZ": "Karta", "ar-EG": "بطاقة", "zh-CN": "刷卡", "zh-TW": "刷卡"},
  "Cash": {"de-DE": "Bar", "fr-FR": "Espèces", "da-DK": "Kontant", "cs-CZ": "Hotovost", "ar-EG": "نقدا", "zh-CN": "现金", "zh-TW": "現金"},
  "Check-in": {"de-DE": "Check-in", "fr-FR": "Contrôle des billets", "da-DK": "Check-in", "cs-CZ": "Odbavení", "ar-EG": "تسجيل الحضور", "zh-CN": "检票", "zh-TW": "驗票"},
  "Check-in opens this many minutes before doors": {"de-DE": "Check-in öffnet so viele Minuten vor Einlass", "fr-FR": "Début du contrôle, en minutes avant l'ouverture des portes", "da-DK": "Check-in åbner så mange minutter før dørene", "cs-CZ": "Odbavení začíná tolik minut před otevřením", "ar-EG": "يبدأ تسجيل الحضور قبل فتح الأبواب بهذه المدة بالدقائق", "zh-CN": "开门前多少分钟开始检票", "zh-TW": "入場前幾分鐘開始驗票"},
  "Check-ins": {"de-DE": "Check-ins", "fr-FR": "Entrées contrôlées", "da-DK": "Check-ins", "cs-CZ": "Odbavení", "ar-EG": "عمليات تسجيل الحضور", "zh-CN": "检票记录", "zh-TW": "驗票紀錄"},
  "Checkout question": {"de-DE": "Frage beim Kauf", "fr-FR": "Question à la commande", "da-DK": "Spørgsmål ved køb", "cs-CZ": "Otázka při nákupu", "ar-EG": "سؤال عند إتمام الشراء", "zh-CN": "结账问题", "zh-TW": "結帳問題"},
  "Checkout questions": {"de-DE": "Fragen beim Kauf", "fr-FR": "Questions à la commande", "da-DK": "Spørgsmål ved køb", "cs-CZ": "Otázky při nákupu", "ar-EG": "أسئلة إتمام الشراء", "zh-CN": "结账问题", "zh-TW": "結帳問題"},
  "Choices, one a line": {"de-DE": "Auswahl, eine pro Zeile", "fr-FR": "Choix, un par ligne", "da-DK": "Valgmuligheder, én pr. linje", "cs-CZ": "Možnosti, každá na vlastní řádek", "ar-EG": "الخيارات، خيار في كل سطر", "zh-CN": "选项，每行一个", "zh-TW": "選項（每行一個）"},
  "Claimed": {"de-DE": "Eingelöst", "fr-FR": "Récupéré", "da-DK": "Taget imod", "cs-CZ": "Uplatněno", "ar-EG": "تمت المطالبة بها", "zh-CN": "已领取", "zh-TW": "已領取"},
  "Club night": {"de-DE": "Clubnacht", "fr-FR": "Soirée club", "da-DK": "Klubaften", "cs-CZ": "Klubová noc", "ar-EG": "ليلة نادٍ", "zh-CN": "俱乐部之夜", "zh-TW": "派對之夜"},
  "Code": {"de-DE": "Code", "fr-FR": "Code", "da-DK": "Kode", "cs-CZ": "Kód", "ar-EG": "الرمز", "zh-CN": "代码", "zh-TW": "代碼"},
  "Code amount": {"de-DE": "Code-Betrag", "fr-FR": "Montant du code", "da-DK": "Kodens beløb", "cs-CZ": "Hodnota kódu", "ar-EG": "قيمة الرمز", "zh-CN": "代码金额", "zh-TW": "代碼折抵金額"},
  "Code applies": {"de-DE": "Code gilt", "fr-FR": "Le code s'applique à", "da-DK": "Koden gælder", "cs-CZ": "Kód platí pro", "ar-EG": "يسري الرمز على", "zh-CN": "代码适用于", "zh-TW": "代碼適用範圍"},
  "Code discount": {"de-DE": "Code-Rabatt", "fr-FR": "Remise du code", "da-DK": "Koderabat", "cs-CZ": "Sleva z kódu", "ar-EG": "خصم الرمز", "zh-CN": "代码优惠", "zh-TW": "代碼折扣"},
  "Code gives": {"de-DE": "Code gewährt", "fr-FR": "Le code donne", "da-DK": "Koden giver", "cs-CZ": "Kód dává", "ar-EG": "ما يمنحه الرمز", "zh-CN": "代码效果", "zh-TW": "代碼優惠"},
  "Code typed": {"de-DE": "Eingegebener Code", "fr-FR": "Code saisi", "da-DK": "Indtastet kode", "cs-CZ": "Zadaný kód", "ar-EG": "الرمز المُدخل", "zh-CN": "输入的代码", "zh-TW": "輸入的代碼"},
  "Code's ticket type": {"de-DE": "Ticketart des Codes", "fr-FR": "Type de billet du code", "da-DK": "Kodens billettype", "cs-CZ": "Typ vstupenky kódu", "ar-EG": "نوع التذكرة للرمز", "zh-CN": "代码对应的票种", "zh-TW": "代碼適用票種"},
  "Codes": {"de-DE": "Codes", "fr-FR": "Codes", "da-DK": "Koder", "cs-CZ": "Kódy", "ar-EG": "الرموز", "zh-CN": "代码", "zh-TW": "代碼"},
  "Comedy": {"de-DE": "Comedy", "fr-FR": "Humour", "da-DK": "Comedy", "cs-CZ": "Komedie", "ar-EG": "كوميديا", "zh-CN": "喜剧", "zh-TW": "喜劇"},
  "Comps": {"de-DE": "Ehrenkarten", "fr-FR": "Invitations", "da-DK": "Billetter uden beregning", "cs-CZ": "Čestné vstupenky", "ar-EG": "الدعوات", "zh-CN": "赠票", "zh-TW": "公關票"},
  "Confirm code": {"de-DE": "Bestätigungscode", "fr-FR": "Code de confirmation", "da-DK": "Bekræftelseskode", "cs-CZ": "Potvrzovací kód", "ar-EG": "رمز التأكيد", "zh-CN": "确认码", "zh-TW": "確認碼"},
  "Confirm your order": {"de-DE": "Bestätige deine Bestellung", "fr-FR": "Confirmez votre commande", "da-DK": "Bekræft din ordre", "cs-CZ": "Potvrďte objednávku", "ar-EG": "أكّد طلبك", "zh-CN": "确认你的订单", "zh-TW": "確認你的訂單"},
  "Confirmed": {"de-DE": "Bestätigt", "fr-FR": "Confirmé", "da-DK": "Bekræftet", "cs-CZ": "Potvrzeno", "ar-EG": "مؤكَّد", "zh-CN": "已确认", "zh-TW": "已確認"},
  "Confirming by email": {"de-DE": "Bestätigung per E-Mail", "fr-FR": "Confirmation par e-mail", "da-DK": "Bekræftes via mail", "cs-CZ": "Potvrzení e-mailem", "ar-EG": "التأكيد عبر البريد الإلكتروني", "zh-CN": "邮件确认中", "zh-TW": "以電子郵件確認"},
  "Contact email": {"de-DE": "Kontakt-E-Mail", "fr-FR": "E-mail de contact", "da-DK": "Kontaktmail", "cs-CZ": "Kontaktní e-mail", "ar-EG": "بريد التواصل", "zh-CN": "联系邮箱", "zh-TW": "聯絡信箱"},
  "Created": {"de-DE": "Erstellt", "fr-FR": "Créé", "da-DK": "Oprettet", "cs-CZ": "Vytvořeno", "ar-EG": "تاريخ الإنشاء", "zh-CN": "创建时间", "zh-TW": "建立時間"},
  "Curfew": {"de-DE": "Sperrstunde", "fr-FR": "Fin de soirée", "da-DK": "Slut senest", "cs-CZ": "Zavírací hodina", "ar-EG": "موعد الإغلاق", "zh-CN": "散场时间", "zh-TW": "散場時間"},
  "Customer": {"de-DE": "Kunde", "fr-FR": "Client", "da-DK": "Kunde", "cs-CZ": "Zákazník", "ar-EG": "العميل", "zh-CN": "顾客", "zh-TW": "顧客"},
  "Customer account": {"de-DE": "Kundenkonto", "fr-FR": "Compte client", "da-DK": "Kundekonto", "cs-CZ": "Zákaznický účet", "ar-EG": "حساب العميل", "zh-CN": "顾客账户", "zh-TW": "顧客帳號"},
  "Customers": {"de-DE": "Kunden", "fr-FR": "Clients", "da-DK": "Kunder", "cs-CZ": "Zákazníci", "ar-EG": "العملاء", "zh-CN": "顾客", "zh-TW": "顧客"},
  "Day": {"de-DE": "Tag", "fr-FR": "Jour", "da-DK": "Dag", "cs-CZ": "Den", "ar-EG": "اليوم", "zh-CN": "日期", "zh-TW": "日"},
  "Day 1": {"de-DE": "Tag 1", "fr-FR": "Jour 1", "da-DK": "Dag 1", "cs-CZ": "Den 1", "ar-EG": "اليوم الأول", "zh-CN": "第1天", "zh-TW": "第 1 天"},
  "Day 2": {"de-DE": "Tag 2", "fr-FR": "Jour 2", "da-DK": "Dag 2", "cs-CZ": "Den 2", "ar-EG": "اليوم الثاني", "zh-CN": "第2天", "zh-TW": "第 2 天"},
  "Day 3": {"de-DE": "Tag 3", "fr-FR": "Jour 3", "da-DK": "Dag 3", "cs-CZ": "Den 3", "ar-EG": "اليوم الثالث", "zh-CN": "第3天", "zh-TW": "第 3 天"},
  "Day admitted": {"de-DE": "Einlasstag", "fr-FR": "Jour d'entrée", "da-DK": "Adgang på dagen", "cs-CZ": "Den vstupu", "ar-EG": "يوم الدخول", "zh-CN": "入场日", "zh-TW": "入場日"},
  "Day ticket": {"de-DE": "Tagesticket", "fr-FR": "Billet journée", "da-DK": "Dagsbillet", "cs-CZ": "Jednodenní vstupenka", "ar-EG": "تذكرة يوم", "zh-CN": "单日票", "zh-TW": "單日票"},
  "Days to pay by transfer": {"de-DE": "Tage für die Überweisung", "fr-FR": "Délai de paiement par virement, en jours", "da-DK": "Dage til at betale via overførsel", "cs-CZ": "Dny na zaplacení převodem", "ar-EG": "مهلة الدفع بالتحويل بالأيام", "zh-CN": "转账付款期限（天）", "zh-TW": "轉帳付款天數"},
  "Description": {"de-DE": "Beschreibung", "fr-FR": "Description", "da-DK": "Beskrivelse", "cs-CZ": "Popis", "ar-EG": "الوصف", "zh-CN": "描述", "zh-TW": "說明"},
  "Details deleted": {"de-DE": "Daten gelöscht", "fr-FR": "Données supprimées", "da-DK": "Oplysninger slettet", "cs-CZ": "Údaje smazány", "ar-EG": "حُذفت البيانات", "zh-CN": "信息已删除", "zh-TW": "資料已刪除"},
  "Didn't come": {"de-DE": "Nicht gekommen", "fr-FR": "Absent", "da-DK": "Mødte ikke op", "cs-CZ": "Nedorazil", "ar-EG": "لم يحضر", "zh-CN": "未到场", "zh-TW": "未到場"},
  "Discount": {"de-DE": "Rabatt", "fr-FR": "Remise", "da-DK": "Rabat", "cs-CZ": "Sleva", "ar-EG": "الخصم", "zh-CN": "优惠", "zh-TW": "折扣"},
  "Discount while live": {"de-DE": "Rabatt, solange aktiv", "fr-FR": "Remise tant qu'actif", "da-DK": "Rabat mens den er aktiv", "cs-CZ": "Sleva po dobu platnosti", "ar-EG": "الخصم أثناء سريانه", "zh-CN": "生效期间优惠", "zh-TW": "啟用期間折扣"},
  "Door": {"de-DE": "Einlass", "fr-FR": "Entrée", "da-DK": "Dør", "cs-CZ": "Vchod", "ar-EG": "الباب", "zh-CN": "门口", "zh-TW": "入場口"},
  "Door devices": {"de-DE": "Einlass-Geräte", "fr-FR": "Appareils de l'entrée", "da-DK": "Enheder ved døren", "cs-CZ": "Zařízení u vchodu", "ar-EG": "أجهزة الباب", "zh-CN": "门口设备", "zh-TW": "入場驗票裝置"},
  "Door payment": {"de-DE": "Zahlung am Einlass", "fr-FR": "Paiement à l'entrée", "da-DK": "Betaling ved døren", "cs-CZ": "Platba u vchodu", "ar-EG": "دفعة عند الباب", "zh-CN": "门口付款", "zh-TW": "現場付款"},
  "Door payments": {"de-DE": "Zahlungen am Einlass", "fr-FR": "Paiements à l'entrée", "da-DK": "Betalinger ved døren", "cs-CZ": "Platby u vchodu", "ar-EG": "المدفوعات عند الباب", "zh-CN": "门口付款记录", "zh-TW": "現場收款"},
  "Door's show": {"de-DE": "Show am Einlass", "fr-FR": "Spectacle de l'entrée", "da-DK": "Dørens arrangement", "cs-CZ": "Akce u vchodu", "ar-EG": "حفل الباب", "zh-CN": "门口当前演出", "zh-TW": "入場口的演出"},
  "Door's show number": {"de-DE": "Shownummer am Einlass", "fr-FR": "Numéro du spectacle de l'entrée", "da-DK": "Dørens arrangementsnummer", "cs-CZ": "Číslo akce u vchodu", "ar-EG": "رقم حفل الباب", "zh-CN": "门口当前演出编号", "zh-TW": "入場口的演出編號"},
  "Doors": {"de-DE": "Einlass", "fr-FR": "Ouverture des portes", "da-DK": "Dørene åbner", "cs-CZ": "Otevření", "ar-EG": "فتح الأبواب", "zh-CN": "开门", "zh-TW": "入場時間"},
  "Doors time changed": {"de-DE": "Einlasszeit geändert", "fr-FR": "Horaire d'ouverture modifié", "da-DK": "Dørtid ændret", "cs-CZ": "Změna času otevření", "ar-EG": "تغيّر موعد فتح الأبواب", "zh-CN": "开门时间已更改", "zh-TW": "入場時間已變更"},
  "Draft": {"de-DE": "Entwurf", "fr-FR": "Brouillon", "da-DK": "Kladde", "cs-CZ": "Koncept", "ar-EG": "مسودة", "zh-CN": "草稿", "zh-TW": "草稿"},
  "Due": {"de-DE": "Fällig", "fr-FR": "Échéance", "da-DK": "Forfalder", "cs-CZ": "Splatnost", "ar-EG": "مستحق", "zh-CN": "到期", "zh-TW": "期限"},
  "Early entry": {"de-DE": "Früher Einlass", "fr-FR": "Entrée anticipée", "da-DK": "Tidlig adgang", "cs-CZ": "Dřívější vstup", "ar-EG": "دخول مبكر", "zh-CN": "提前入场", "zh-TW": "提早入場"},
  "Email": {"de-DE": "E-Mail", "fr-FR": "E-mail", "da-DK": "Mail", "cs-CZ": "E-mail", "ar-EG": "البريد الإلكتروني", "zh-CN": "邮箱", "zh-TW": "電子郵件"},
  "Emails": {"de-DE": "E-Mails", "fr-FR": "E-mails", "da-DK": "Mails", "cs-CZ": "E-maily", "ar-EG": "الرسائل", "zh-CN": "邮件", "zh-TW": "電子郵件"},
  "Ends": {"de-DE": "Endet", "fr-FR": "Fin", "da-DK": "Slutter", "cs-CZ": "Konec", "ar-EG": "ينتهي", "zh-CN": "结束", "zh-TW": "結束"},
  "Every show in": {"de-DE": "Alle Shows in", "fr-FR": "Tous les spectacles de", "da-DK": "Alle arrangementer i", "cs-CZ": "Všechny akce v", "ar-EG": "كل الحفلات في", "zh-CN": "该场地的全部演出", "zh-TW": "適用場地的所有演出"},
  "Everyone": {"de-DE": "Alle", "fr-FR": "Tout le monde", "da-DK": "Alle", "cs-CZ": "Všichni", "ar-EG": "الجميع", "zh-CN": "所有人", "zh-TW": "所有人"},
  "Expired": {"de-DE": "Abgelaufen", "fr-FR": "Expiré", "da-DK": "Udløbet", "cs-CZ": "Vypršelo", "ar-EG": "انتهت صلاحيته", "zh-CN": "已过期", "zh-TW": "已過期"},
  "Festival": {"de-DE": "Festival", "fr-FR": "Festival", "da-DK": "Festival", "cs-CZ": "Festival", "ar-EG": "مهرجان", "zh-CN": "音乐节", "zh-TW": "音樂節"},
  "Festival timetable": {"de-DE": "Festival-Ablauf", "fr-FR": "Horaires du festival", "da-DK": "Festivalprogram", "cs-CZ": "Festivalový program", "ar-EG": "جدول المهرجان", "zh-CN": "音乐节时间表", "zh-TW": "音樂節時間表"},
  "First order": {"de-DE": "Erste Bestellung", "fr-FR": "Première commande", "da-DK": "Første ordre", "cs-CZ": "První objednávka", "ar-EG": "أول طلب", "zh-CN": "首个订单", "zh-TW": "第一筆訂單"},
  "First order number": {"de-DE": "Erste Bestellnummer", "fr-FR": "Premier numéro de commande", "da-DK": "Første ordrenummer", "cs-CZ": "Číslo první objednávky", "ar-EG": "رقم أول طلب", "zh-CN": "起始订单号", "zh-TW": "起始訂單編號"},
  "For": {"de-DE": "Für", "fr-FR": "Pour", "da-DK": "Til", "cs-CZ": "Pro", "ar-EG": "لصالح", "zh-CN": "用于", "zh-TW": "適用"},
  "For each ticket": {"de-DE": "Pro Ticket", "fr-FR": "Par billet", "da-DK": "Pr. billet", "cs-CZ": "Za každou vstupenku", "ar-EG": "لكل تذكرة", "zh-CN": "每张票", "zh-TW": "每張票"},
  "Getting in": {"de-DE": "So kommst du rein", "fr-FR": "Accès à la salle", "da-DK": "Adgang", "cs-CZ": "Vstup", "ar-EG": "الدخول", "zh-CN": "入场须知", "zh-TW": "入場須知"},
  "Getting there": {"de-DE": "Anfahrt", "fr-FR": "Venir à la salle", "da-DK": "Sådan kommer du hertil", "cs-CZ": "Jak se k nám dostat", "ar-EG": "الوصول إلينا", "zh-CN": "交通指南", "zh-TW": "交通方式"},
  "Gig": {"de-DE": "Konzert", "fr-FR": "Concert", "da-DK": "Koncert", "cs-CZ": "Koncert", "ar-EG": "حفلة موسيقية", "zh-CN": "演出", "zh-TW": "音樂演出"},
  "Going out": {"de-DE": "Wird versendet", "fr-FR": "Envoi en cours", "da-DK": "Sendes", "cs-CZ": "Odesílá se", "ar-EG": "قيد الإرسال", "zh-CN": "发送中", "zh-TW": "寄送中"},
  "Good to know": {"de-DE": "Gut zu wissen", "fr-FR": "Bon à savoir", "da-DK": "Godt at vide", "cs-CZ": "Dobré vědět", "ar-EG": "معلومات مفيدة", "zh-CN": "温馨提示", "zh-TW": "小提醒"},
  "Guest": {"de-DE": "Gast", "fr-FR": "Invité", "da-DK": "Gæst", "cs-CZ": "Host", "ar-EG": "ضيف", "zh-CN": "嘉宾", "zh-TW": "來賓"},
  "Guest list": {"de-DE": "Gästeliste", "fr-FR": "Liste d'invités", "da-DK": "Gæsteliste", "cs-CZ": "Seznam hostů", "ar-EG": "قائمة الضيوف", "zh-CN": "嘉宾名单", "zh-TW": "貴賓名單"},
  "Guest list closes": {"de-DE": "Gästeliste schließt", "fr-FR": "Clôture de la liste d'invités", "da-DK": "Gæstelisten lukker", "cs-CZ": "Seznam hostů se uzavírá", "ar-EG": "إغلاق قائمة الضيوف", "zh-CN": "嘉宾名单截止", "zh-TW": "貴賓名單截止"},
  "Guest lists": {"de-DE": "Gästelisten", "fr-FR": "Listes d'invités", "da-DK": "Gæstelister", "cs-CZ": "Seznamy hostů", "ar-EG": "قوائم الضيوف", "zh-CN": "嘉宾名单", "zh-TW": "貴賓名單"},
  "Guest-list places": {"de-DE": "Plätze auf der Gästeliste", "fr-FR": "Places sur liste d'invités", "da-DK": "Pladser på gæstelisten", "cs-CZ": "Místa na seznamu hostů", "ar-EG": "أماكن قائمة الضيوف", "zh-CN": "嘉宾名额", "zh-TW": "貴賓名額"},
  "Held until": {"de-DE": "Reserviert bis", "fr-FR": "Réservé jusqu'à", "da-DK": "Reserveret til", "cs-CZ": "Rezervováno do", "ar-EG": "محجوزة حتى", "zh-CN": "保留至", "zh-TW": "保留至"},
  "Holder's account": {"de-DE": "Konto des Ticketinhabers", "fr-FR": "Compte du détenteur", "da-DK": "Indehaverens konto", "cs-CZ": "Účet držitele", "ar-EG": "حساب حامل التذكرة", "zh-CN": "持票人账户", "zh-TW": "持票人帳號"},
  "Holder's email": {"de-DE": "E-Mail des Ticketinhabers", "fr-FR": "E-mail du détenteur", "da-DK": "Indehaverens mail", "cs-CZ": "E-mail držitele", "ar-EG": "بريد حامل التذكرة", "zh-CN": "持票人邮箱", "zh-TW": "持票人信箱"},
  "Holder's reminder": {"de-DE": "Erinnerung an Ticketinhaber", "fr-FR": "Rappel au détenteur", "da-DK": "Påmindelse til indehaveren", "cs-CZ": "Připomínka držiteli", "ar-EG": "تذكير حامل التذكرة", "zh-CN": "持票人提醒", "zh-TW": "持票人提醒"},
  "Hours a friend has to accept a ticket": {"de-DE": "Stunden zum Annehmen eines weitergegebenen Tickets", "fr-FR": "Délai pour qu'un proche accepte un billet, en heures", "da-DK": "Timer en ven har til at acceptere en billet", "cs-CZ": "Lhůta pro přijetí vstupenky kamarádem (hodiny)", "ar-EG": "مهلة قبول الصديق للتذكرة بالساعات", "zh-CN": "朋友接收门票的时限（小时）", "zh-TW": "朋友接受票券的時限（小時）"},
  "Hours a waitlist offer lasts": {"de-DE": "Stunden, die ein Wartelisten-Angebot gilt", "fr-FR": "Durée d'une offre de liste d'attente, en heures", "da-DK": "Timer et ventelistetilbud gælder", "cs-CZ": "Platnost nabídky z čekací listiny (hodiny)", "ar-EG": "مدة عرض قائمة الانتظار بالساعات", "zh-CN": "候补邀约的有效时长（小时）", "zh-TW": "候補釋票保留時數"},
  "Hours before a sale the reminder goes": {"de-DE": "Stunden vor Verkaufsstart für die Erinnerung", "fr-FR": "Envoi du rappel, en heures avant l'ouverture des ventes", "da-DK": "Timer før salgsstart påmindelsen sendes", "cs-CZ": "Připomínka před začátkem prodeje (hodiny)", "ar-EG": "موعد إرسال التذكير قبل بدء البيع بالساعات", "zh-CN": "开售前多少小时发送提醒", "zh-TW": "開賣前幾小時寄出提醒"},
  "Hours of grace before unpaid tickets go back on sale": {"de-DE": "Kulanzstunden, bevor unbezahlte Tickets wieder in den Verkauf gehen", "fr-FR": "Délai avant la remise en vente des billets impayés, en heures", "da-DK": "Timers henstand før ubetalte billetter kommer til salg igen", "cs-CZ": "Odklad před vrácením nezaplacených vstupenek do prodeje (hodiny)", "ar-EG": "مهلة السماح بالساعات قبل عودة التذاكر غير المدفوعة إلى البيع", "zh-CN": "未付款门票重新开售前的宽限时长（小时）", "zh-TW": "未付款票券重新開賣前的寬限時數"},
  "How": {"de-DE": "Wie", "fr-FR": "Comment", "da-DK": "Hvordan", "cs-CZ": "Jak", "ar-EG": "الطريقة", "zh-CN": "方式", "zh-TW": "方式"},
  "How many": {"de-DE": "Wie viele", "fr-FR": "Combien", "da-DK": "Antal", "cs-CZ": "Kolik", "ar-EG": "العدد", "zh-CN": "数量", "zh-TW": "數量"},
  "In": {"de-DE": "Eingelassen", "fr-FR": "Entré", "da-DK": "Inde", "cs-CZ": "Uvnitř", "ar-EG": "دخل", "zh-CN": "已入场", "zh-TW": "已入場"},
  "In at": {"de-DE": "Eingelassen um", "fr-FR": "Entré à", "da-DK": "Inde kl.", "cs-CZ": "Vstup v", "ar-EG": "وقت الدخول", "zh-CN": "入场时间", "zh-TW": "入場於"},
  "In checkout": {"de-DE": "Im Kaufvorgang", "fr-FR": "Commande en cours", "da-DK": "I kassen", "cs-CZ": "Při nákupu", "ar-EG": "في إتمام الشراء", "zh-CN": "结账中", "zh-TW": "結帳中"},
  "In use": {"de-DE": "Im Einsatz", "fr-FR": "Utilisé", "da-DK": "I brug", "cs-CZ": "Používá se", "ar-EG": "قيد الاستخدام", "zh-CN": "使用中", "zh-TW": "使用中"},
  "Joined": {"de-DE": "Eingetragen", "fr-FR": "Inscrit le", "da-DK": "Skrevet op", "cs-CZ": "Přihlášeno", "ar-EG": "تاريخ الانضمام", "zh-CN": "加入时间", "zh-TW": "加入時間"},
  "Kept after the move": {"de-DE": "Nach Verlegung behalten", "fr-FR": "Conservé après le changement de date", "da-DK": "Beholdt efter flytningen", "cs-CZ": "Ponecháno po přesunu", "ar-EG": "احتُفظ بها بعد تغيير الموعد", "zh-CN": "改期后保留", "zh-TW": "改期後保留"},
  "Kind": {"de-DE": "Art", "fr-FR": "Genre", "da-DK": "Slags", "cs-CZ": "Druh", "ar-EG": "الصنف", "zh-CN": "类别", "zh-TW": "類別"},
  "Language": {"de-DE": "Sprache", "fr-FR": "Langue", "da-DK": "Sprog", "cs-CZ": "Jazyk", "ar-EG": "اللغة", "zh-CN": "语言", "zh-TW": "語言"},
  "Last entry": {"de-DE": "Letzter Einlass", "fr-FR": "Dernière entrée", "da-DK": "Sidste adgang", "cs-CZ": "Poslední vstup", "ar-EG": "آخر دخول", "zh-CN": "最晚入场", "zh-TW": "最後入場"},
  "Left": {"de-DE": "Abgemeldet", "fr-FR": "Restant", "da-DK": "Tilbage", "cs-CZ": "Zbývá", "ar-EG": "المتبقي", "zh-CN": "剩余", "zh-TW": "剩餘"},
  "Let go": {"de-DE": "Freigegeben", "fr-FR": "Abandonné", "da-DK": "Frigivet", "cs-CZ": "Uvolněno", "ar-EG": "أُفرج عنها", "zh-CN": "已放弃", "zh-TW": "已釋出"},
  "Let in by": {"de-DE": "Eingelassen von", "fr-FR": "Entrée validée par", "da-DK": "Lukket ind af", "cs-CZ": "Kdo vpustil", "ar-EG": "أدخله", "zh-CN": "放行人", "zh-TW": "放行人員"},
  "Link code": {"de-DE": "Link-Code", "fr-FR": "Code du lien", "da-DK": "Linkkode", "cs-CZ": "Kód odkazu", "ar-EG": "رمز الرابط", "zh-CN": "链接码", "zh-TW": "連結代碼"},
  "Link stopped": {"de-DE": "Link deaktiviert", "fr-FR": "Lien désactivé", "da-DK": "Link stoppet", "cs-CZ": "Odkaz zrušen", "ar-EG": "أُوقف الرابط", "zh-CN": "链接已停用", "zh-TW": "連結已停用"},
  "Live": {"de-DE": "Live", "fr-FR": "Actif", "da-DK": "Aktiv", "cs-CZ": "Aktivní", "ar-EG": "فعّال", "zh-CN": "已上线", "zh-TW": "上線中"},
  "Made": {"de-DE": "Gekauft", "fr-FR": "Créé le", "da-DK": "Oprettet", "cs-CZ": "Vytvořeno", "ar-EG": "أُنشئ", "zh-CN": "创建时间", "zh-TW": "建立於"},
  "Manage": {"de-DE": "Verwalten", "fr-FR": "Gérer", "da-DK": "Administrer", "cs-CZ": "Spravovat", "ar-EG": "إدارة", "zh-CN": "管理", "zh-TW": "管理"},
  "Message": {"de-DE": "Nachricht", "fr-FR": "Message", "da-DK": "Besked", "cs-CZ": "Zpráva", "ar-EG": "الرسالة", "zh-CN": "消息", "zh-TW": "訊息"},
  "Message as sent": {"de-DE": "Nachricht wie gesendet", "fr-FR": "Message tel qu'envoyé", "da-DK": "Besked som sendt", "cs-CZ": "Zpráva, jak byla odeslána", "ar-EG": "الرسالة كما أُرسلت", "zh-CN": "消息原文", "zh-TW": "寄出的訊息內容"},
  "Message to buyers": {"de-DE": "Nachricht an Käufer", "fr-FR": "Message aux acheteurs", "da-DK": "Besked til købere", "cs-CZ": "Zpráva kupujícím", "ar-EG": "رسالة إلى المشترين", "zh-CN": "给购票人的消息", "zh-TW": "給購票人的訊息"},
  "Messages to buyers": {"de-DE": "Nachrichten an Käufer", "fr-FR": "Messages aux acheteurs", "da-DK": "Beskeder til købere", "cs-CZ": "Zprávy kupujícím", "ar-EG": "رسائل إلى المشترين", "zh-CN": "给购票人的消息", "zh-TW": "給購票人的訊息"},
  "Minutes a checkout holds tickets": {"de-DE": "Minuten, die der Kaufvorgang Tickets reserviert", "fr-FR": "Réservation des billets pendant la commande, en minutes", "da-DK": "Minutter et køb holder på billetterne", "cs-CZ": "Jak dlouho nákup drží vstupenky (minuty)", "ar-EG": "مدة حجز التذاكر أثناء إتمام الشراء بالدقائق", "zh-CN": "结账时保留门票的时长（分钟）", "zh-TW": "結帳時保留票券的分鐘數"},
  "Missed": {"de-DE": "Verpasst", "fr-FR": "Manqué", "da-DK": "Ikke nået", "cs-CZ": "Zmeškáno", "ar-EG": "فاته الحفل", "zh-CN": "已错过", "zh-TW": "錯過"},
  "Money back, tickets kept": {"de-DE": "Geld zurück, Tickets behalten", "fr-FR": "Remboursé, billets conservés", "da-DK": "Penge tilbage, billetter beholdt", "cs-CZ": "Peníze zpět, vstupenky ponechány", "ar-EG": "استرداد المال مع الاحتفاظ بالتذاكر", "zh-CN": "退款，门票保留", "zh-TW": "退款，保留票券"},
  "Money back, tickets stay": {"de-DE": "Geld zurück, Tickets bleiben gültig", "fr-FR": "Remboursé, billets toujours valables", "da-DK": "Penge tilbage, billetterne gælder stadig", "cs-CZ": "Peníze zpět, vstupenky platí dál", "ar-EG": "استرداد المال وتبقى التذاكر", "zh-CN": "退款，门票照常有效", "zh-TW": "退款，票券仍有效"},
  "Must be answered": {"de-DE": "Pflichtfrage", "fr-FR": "Réponse obligatoire", "da-DK": "Skal besvares", "cs-CZ": "Povinná odpověď", "ar-EG": "إجابته مطلوبة", "zh-CN": "必答", "zh-TW": "必填"},
  "Name": {"de-DE": "Name", "fr-FR": "Nom", "da-DK": "Navn", "cs-CZ": "Jméno", "ar-EG": "الاسم", "zh-CN": "名称", "zh-TW": "名稱"},
  "Name on the ticket": {"de-DE": "Name auf dem Ticket", "fr-FR": "Nom sur le billet", "da-DK": "Navn på billetten", "cs-CZ": "Jméno na vstupence", "ar-EG": "الاسم على التذكرة", "zh-CN": "票面姓名", "zh-TW": "票面姓名"},
  "News from the venue": {"de-DE": "Neuigkeiten von uns", "fr-FR": "Nouvelles de la salle", "da-DK": "Nyt fra spillestedet", "cs-CZ": "Novinky z klubu", "ar-EG": "أخبار من المكان", "zh-CN": "场馆动态", "zh-TW": "場館消息"},
  "No charge": {"de-DE": "Ohne Kosten", "fr-FR": "Sans frais", "da-DK": "Uden beregning", "cs-CZ": "Bez poplatku", "ar-EG": "دون رسوم", "zh-CN": "不收费", "zh-TW": "不收費"},
  "No longer needed": {"de-DE": "Nicht mehr nötig", "fr-FR": "Plus nécessaire", "da-DK": "Ikke længere nødvendig", "cs-CZ": "Už není potřeba", "ar-EG": "لم تعد مطلوبة", "zh-CN": "已不再需要", "zh-TW": "已不需要"},
  "No transfers in the last days before a show": {"de-DE": "Keine Überweisung in den letzten Tagen vor der Show", "fr-FR": "Pas de virement dans les derniers jours avant un spectacle", "da-DK": "Ingen overførsler de sidste dage før et arrangement", "cs-CZ": "Žádné převody v posledních dnech před akcí", "ar-EG": "لا تحويلات في الأيام الأخيرة قبل الحفل", "zh-CN": "演出前最后几天不接受转账", "zh-TW": "演出前幾天內不接受轉帳"},
  "Not at the door": {"de-DE": "Nicht am Einlass", "fr-FR": "Pas à l'entrée", "da-DK": "Ikke ved døren", "cs-CZ": "Ne u vchodu", "ar-EG": "ليس عند الباب", "zh-CN": "不可在门口", "zh-TW": "不開放現場"},
  "Not by transfer": {"de-DE": "Nicht per Überweisung", "fr-FR": "Pas par virement", "da-DK": "Ikke via overførsel", "cs-CZ": "Ne převodem", "ar-EG": "ليس بالتحويل", "zh-CN": "不可转账", "zh-TW": "不接受轉帳"},
  "Not in": {"de-DE": "Nicht eingelassen", "fr-FR": "Pas entré", "da-DK": "Ikke inde", "cs-CZ": "Není uvnitř", "ar-EG": "لم يدخل", "zh-CN": "未入场", "zh-TW": "未入場"},
  "Not sent": {"de-DE": "Nicht gesendet", "fr-FR": "Non envoyé", "da-DK": "Ikke sendt", "cs-CZ": "Neodesláno", "ar-EG": "لم تُرسل", "zh-CN": "未发送", "zh-TW": "未寄出"},
  "Not yet checked in": {"de-DE": "Noch nicht eingecheckt", "fr-FR": "Pas encore contrôlé", "da-DK": "Ikke tjekket ind endnu", "cs-CZ": "Zatím neodbaveno", "ar-EG": "لم يُسجَّل حضوره بعد", "zh-CN": "尚未检票", "zh-TW": "尚未驗票"},
  "Note": {"de-DE": "Notiz", "fr-FR": "Note", "da-DK": "Note", "cs-CZ": "Poznámka", "ar-EG": "ملاحظة", "zh-CN": "备注", "zh-TW": "備註"},
  "Note on the cancel": {"de-DE": "Notiz zur Stornierung", "fr-FR": "Note sur l'annulation", "da-DK": "Note til annulleringen", "cs-CZ": "Poznámka ke zrušení", "ar-EG": "ملاحظة على الإلغاء", "zh-CN": "取消备注", "zh-TW": "取消備註"},
  "Number (running)": {"de-DE": "Laufende Nummer", "fr-FR": "Numéro (à la suite)", "da-DK": "Nummer (løbende)", "cs-CZ": "Číslo (průběžné)", "ar-EG": "الرقم (متسلسل)", "zh-CN": "流水编号", "zh-TW": "流水號"},
  "Off": {"de-DE": "Aus", "fr-FR": "Désactivé", "da-DK": "Fra", "cs-CZ": "Vypnuto", "ar-EG": "متوقف", "zh-CN": "关闭", "zh-TW": "關閉"},
  "Offer": {"de-DE": "Angebot", "fr-FR": "Offre", "da-DK": "Tilbud", "cs-CZ": "Nabídka", "ar-EG": "العرض", "zh-CN": "邀约", "zh-TW": "候補釋票"},
  "Offer runs until": {"de-DE": "Angebot gilt bis", "fr-FR": "Offre valable jusqu'à", "da-DK": "Tilbuddet gælder til", "cs-CZ": "Nabídka platí do", "ar-EG": "العرض ساري حتى", "zh-CN": "邀约有效至", "zh-TW": "釋票保留至"},
  "Offered": {"de-DE": "Angeboten", "fr-FR": "Proposé", "da-DK": "Tilbudt", "cs-CZ": "Nabídnuto", "ar-EG": "عُرضت", "zh-CN": "已发出邀约", "zh-TW": "已通知"},
  "On": {"de-DE": "An", "fr-FR": "Activé", "da-DK": "Til", "cs-CZ": "Zapnuto", "ar-EG": "يعمل", "zh-CN": "开启", "zh-TW": "開啟"},
  "On sale": {"de-DE": "Im Verkauf", "fr-FR": "En vente", "da-DK": "Til salg", "cs-CZ": "V prodeji", "ar-EG": "معروضة للبيع", "zh-CN": "售票中", "zh-TW": "販售中"},
  "On sale at most": {"de-DE": "Höchstens im Verkauf", "fr-FR": "Mis en vente au maximum", "da-DK": "Højst til salg", "cs-CZ": "V prodeji nejvýše", "ar-EG": "الحد الأقصى المعروض للبيع", "zh-CN": "最多开售", "zh-TW": "最多販售"},
  "On sale from": {"de-DE": "Im Verkauf ab", "fr-FR": "En vente à partir de", "da-DK": "Til salg fra", "cs-CZ": "V prodeji od", "ar-EG": "البيع يبدأ في", "zh-CN": "开售时间", "zh-TW": "開賣時間"},
  "On sale soon": {"de-DE": "Bald im Verkauf", "fr-FR": "Bientôt en vente", "da-DK": "Snart til salg", "cs-CZ": "Brzy v prodeji", "ar-EG": "البيع قريبا", "zh-CN": "即将开售", "zh-TW": "即將開賣"},
  "On sale until": {"de-DE": "Im Verkauf bis", "fr-FR": "En vente jusqu'à", "da-DK": "Til salg til", "cs-CZ": "V prodeji do", "ar-EG": "البيع حتى", "zh-CN": "停售时间", "zh-TW": "販售至"},
  "On stage": {"de-DE": "Beginn", "fr-FR": "Sur scène", "da-DK": "På scenen", "cs-CZ": "Na pódiu", "ar-EG": "على المسرح", "zh-CN": "登台", "zh-TW": "演出開始"},
  "Once an order": {"de-DE": "Einmal pro Bestellung", "fr-FR": "Une fois par commande", "da-DK": "Én gang pr. ordre", "cs-CZ": "Jednou za objednávku", "ar-EG": "مرة لكل طلب", "zh-CN": "每单一次", "zh-TW": "每筆訂單一次"},
  "One room": {"de-DE": "Ein Raum", "fr-FR": "Une seule salle", "da-DK": "Én sal", "cs-CZ": "Jeden sál", "ar-EG": "قاعة واحدة", "zh-CN": "单个厅", "zh-TW": "單一廳"},
  "One ticket type": {"de-DE": "Eine Ticketart", "fr-FR": "Un seul type de billet", "da-DK": "Én billettype", "cs-CZ": "Jeden typ vstupenky", "ar-EG": "نوع تذكرة واحد", "zh-CN": "单一票种", "zh-TW": "單一票種"},
  "Online": {"de-DE": "Online", "fr-FR": "En ligne", "da-DK": "Online", "cs-CZ": "Online", "ar-EG": "عبر الإنترنت", "zh-CN": "线上", "zh-TW": "線上"},
  "Order": {"de-DE": "Bestellung", "fr-FR": "Commande", "da-DK": "Ordre", "cs-CZ": "Objednávka", "ar-EG": "الطلب", "zh-CN": "订单", "zh-TW": "訂單"},
  "Orders": {"de-DE": "Bestellungen", "fr-FR": "Commandes", "da-DK": "Ordrer", "cs-CZ": "Objednávky", "ar-EG": "الطلبات", "zh-CN": "订单", "zh-TW": "訂單"},
  "Orders each week": {"de-DE": "Bestellungen pro Woche", "fr-FR": "Commandes par semaine", "da-DK": "Ordrer pr. uge", "cs-CZ": "Objednávky po týdnech", "ar-EG": "الطلبات كل أسبوع", "zh-CN": "每周订单", "zh-TW": "每週訂單"},
  "Orders it went to": {"de-DE": "Bestellungen, an die sie ging", "fr-FR": "Commandes destinataires", "da-DK": "Ordrer den gik til", "cs-CZ": "Objednávky, kam byla odeslána", "ar-EG": "الطلبات التي وصلتها", "zh-CN": "发送到的订单", "zh-TW": "寄送的訂單"},
  "Orders to pay at the door": {"de-DE": "Bestellungen mit Zahlung am Einlass", "fr-FR": "Commandes à régler à l'entrée", "da-DK": "Ordrer der betales ved døren", "cs-CZ": "Objednávky k zaplacení u vchodu", "ar-EG": "طلبات تُدفع عند الباب", "zh-CN": "门口付款的订单", "zh-TW": "現場付款訂單"},
  "Other": {"de-DE": "Sonstiges", "fr-FR": "Autre", "da-DK": "Andet", "cs-CZ": "Jiné", "ar-EG": "أخرى", "zh-CN": "其他", "zh-TW": "其他"},
  "Overview": {"de-DE": "Übersicht", "fr-FR": "Vue d'ensemble", "da-DK": "Overblik", "cs-CZ": "Přehled", "ar-EG": "نظرة عامة", "zh-CN": "概览", "zh-TW": "總覽"},
  "Owed": {"de-DE": "Offen", "fr-FR": "Reste dû", "da-DK": "Skyldigt", "cs-CZ": "K úhradě", "ar-EG": "المبلغ المستحق", "zh-CN": "待付", "zh-TW": "待付"},
  "Owed at the door": {"de-DE": "Am Einlass offen", "fr-FR": "Reste dû à l'entrée", "da-DK": "Skyldigt ved døren", "cs-CZ": "K úhradě u vchodu", "ar-EG": "المستحق عند الباب", "zh-CN": "门口待付", "zh-TW": "現場待付"},
  "Paid": {"de-DE": "Bezahlt", "fr-FR": "Payé", "da-DK": "Betalt", "cs-CZ": "Zaplaceno", "ar-EG": "مدفوع", "zh-CN": "已付款", "zh-TW": "已付款"},
  "Paid by": {"de-DE": "Bezahlt mit", "fr-FR": "Payé par", "da-DK": "Betalt med", "cs-CZ": "Způsob platby", "ar-EG": "دُفع عبر", "zh-CN": "付款方式", "zh-TW": "付款方式"},
  "Paid for": {"de-DE": "Beglichen", "fr-FR": "Payé pour", "da-DK": "Betalt for", "cs-CZ": "Zaplaceno za", "ar-EG": "مدفوعة الثمن", "zh-CN": "付款项目", "zh-TW": "已付款項目"},
  "Paid in": {"de-DE": "Eingezahlt", "fr-FR": "Encaissé", "da-DK": "Indbetalt", "cs-CZ": "Přijatá platba", "ar-EG": "المبلغ المدفوع", "zh-CN": "已付金额", "zh-TW": "已付金額"},
  "Paid on": {"de-DE": "Bezahlt am", "fr-FR": "Payé le", "da-DK": "Betalt den", "cs-CZ": "Zaplaceno dne", "ar-EG": "تاريخ الدفع", "zh-CN": "付款日期", "zh-TW": "付款日期"},
  "Part of a waitlist offer not claimed": {"de-DE": "Teil eines Wartelisten-Angebots nicht eingelöst", "fr-FR": "Partie non récupérée d'une offre de liste d'attente", "da-DK": "Del af et ventelistetilbud, der ikke blev taget imod", "cs-CZ": "Neuplatněná část nabídky z čekací listiny", "ar-EG": "جزء من عرض قائمة الانتظار لم يُطالَب به", "zh-CN": "候补邀约中未领取的部分", "zh-TW": "候補釋票未領取的部分"},
  "Pay at the door": {"de-DE": "Zahlung am Einlass", "fr-FR": "Payer à l'entrée", "da-DK": "Betal ved døren", "cs-CZ": "Platba u vchodu", "ar-EG": "الدفع عند الباب", "zh-CN": "门口付款", "zh-TW": "現場付款"},
  "Pay by": {"de-DE": "Zahlen bis", "fr-FR": "À payer avant le", "da-DK": "Betal senest", "cs-CZ": "Zaplatit do", "ar-EG": "آخر موعد للدفع", "zh-CN": "付款截止", "zh-TW": "付款期限"},
  "Payment": {"de-DE": "Zahlung", "fr-FR": "Paiement", "da-DK": "Betaling", "cs-CZ": "Platba", "ar-EG": "الدفع", "zh-CN": "付款", "zh-TW": "付款"},
  "Payment received": {"de-DE": "Zahlung erhalten", "fr-FR": "Paiement reçu", "da-DK": "Betaling modtaget", "cs-CZ": "Platba přijata", "ar-EG": "تم استلام الدفعة", "zh-CN": "已收到付款", "zh-TW": "已收到款項"},
  "Payments": {"de-DE": "Zahlungen", "fr-FR": "Paiements", "da-DK": "Betalinger", "cs-CZ": "Platby", "ar-EG": "المدفوعات", "zh-CN": "付款记录", "zh-TW": "款項"},
  "People": {"de-DE": "Personen", "fr-FR": "Personnes", "da-DK": "Personer", "cs-CZ": "Lidé", "ar-EG": "الأشخاص", "zh-CN": "人数", "zh-TW": "人數"},
  "Percent off": {"de-DE": "Prozent Rabatt", "fr-FR": "Remise en pourcentage", "da-DK": "Procent rabat", "cs-CZ": "Sleva v procentech", "ar-EG": "نسبة الخصم", "zh-CN": "折扣比例", "zh-TW": "折扣百分比"},
  "Place": {"de-DE": "Platz", "fr-FR": "Place", "da-DK": "Plads", "cs-CZ": "Místo", "ar-EG": "المكان", "zh-CN": "排位", "zh-TW": "順位"},
  "Placed": {"de-DE": "Aufgegeben", "fr-FR": "Passée le", "da-DK": "Afgivet", "cs-CZ": "Zadáno", "ar-EG": "تاريخ الطلب", "zh-CN": "下单时间", "zh-TW": "下單時間"},
  "Plus": {"de-DE": "Begleitung", "fr-FR": "En plus", "da-DK": "Plus", "cs-CZ": "Plus", "ar-EG": "إضافة", "zh-CN": "另加", "zh-TW": "攜伴人數"},
  "Position": {"de-DE": "Position", "fr-FR": "Position", "da-DK": "Placering", "cs-CZ": "Pořadí", "ar-EG": "الترتيب", "zh-CN": "位次", "zh-TW": "排序"},
  "Poster": {"de-DE": "Plakat", "fr-FR": "Affiche", "da-DK": "Plakat", "cs-CZ": "Plakát", "ar-EG": "الملصق", "zh-CN": "海报", "zh-TW": "海報"},
  "Poster colour": {"de-DE": "Posterfarbe", "fr-FR": "Couleur de l'affiche", "da-DK": "Plakatfarve", "cs-CZ": "Barva plakátu", "ar-EG": "لون الملصق", "zh-CN": "海报颜色", "zh-TW": "海報顏色"},
  "Poster style": {"de-DE": "Plakatstil", "fr-FR": "Style d'affiche", "da-DK": "Plakatstil", "cs-CZ": "Styl plakátu", "ar-EG": "نمط الملصق", "zh-CN": "海报样式", "zh-TW": "海報風格"},
  "Postponed": {"de-DE": "Verschoben", "fr-FR": "Reporté", "da-DK": "Udskudt", "cs-CZ": "Odloženo", "ar-EG": "مؤجَّل", "zh-CN": "已延期", "zh-TW": "延期"},
  "Presale": {"de-DE": "Vorverkauf", "fr-FR": "Prévente", "da-DK": "Forsalg", "cs-CZ": "Předprodej", "ar-EG": "بيع مسبق", "zh-CN": "预售", "zh-TW": "預售"},
  "Presale opens": {"de-DE": "Vorverkauf startet", "fr-FR": "Ouverture de la prévente", "da-DK": "Forsalget åbner", "cs-CZ": "Začátek předprodeje", "ar-EG": "بدء البيع المسبق", "zh-CN": "预售开始", "zh-TW": "預售開始"},
  "Price": {"de-DE": "Preis", "fr-FR": "Prix", "da-DK": "Pris", "cs-CZ": "Cena", "ar-EG": "السعر", "zh-CN": "价格", "zh-TW": "票價"},
  "Price while live": {"de-DE": "Preis, solange aktiv", "fr-FR": "Prix tant qu'actif", "da-DK": "Pris mens den er aktiv", "cs-CZ": "Cena po dobu platnosti", "ar-EG": "السعر أثناء سريانه", "zh-CN": "生效期间价格", "zh-TW": "上線期間票價"},
  "Published": {"de-DE": "Veröffentlicht", "fr-FR": "Publié", "da-DK": "Offentliggjort", "cs-CZ": "Zveřejněno", "ar-EG": "منشور", "zh-CN": "已发布", "zh-TW": "已發布"},
  "Question": {"de-DE": "Frage", "fr-FR": "Question", "da-DK": "Spørgsmål", "cs-CZ": "Otázka", "ar-EG": "السؤال", "zh-CN": "问题", "zh-TW": "問題"},
  "Questions people ask": {"de-DE": "Häufige Fragen", "fr-FR": "Questions fréquentes", "da-DK": "Ofte stillede spørgsmål", "cs-CZ": "Časté otázky", "ar-EG": "أسئلة شائعة", "zh-CN": "常见问题", "zh-TW": "常見問題"},
  "Re-entry": {"de-DE": "Wiedereinlass", "fr-FR": "Sortie et retour", "da-DK": "Genindgang", "cs-CZ": "Opakovaný vstup", "ar-EG": "إعادة الدخول", "zh-CN": "再次入场", "zh-TW": "再入場"},
  "Receipt": {"de-DE": "Quittung", "fr-FR": "Reçu", "da-DK": "Kvittering", "cs-CZ": "Účtenka", "ar-EG": "الإيصال", "zh-CN": "收据", "zh-TW": "收據"},
  "Receipts": {"de-DE": "Quittungen", "fr-FR": "Reçus", "da-DK": "Kvitteringer", "cs-CZ": "Účtenky", "ar-EG": "الإيصالات", "zh-CN": "收据", "zh-TW": "收據"},
  "Received": {"de-DE": "Erhalten", "fr-FR": "Reçu le", "da-DK": "Modtaget", "cs-CZ": "Obdrženo", "ar-EG": "تم الاستلام", "zh-CN": "已收到", "zh-TW": "已收到"},
  "Recorded": {"de-DE": "Erfasst", "fr-FR": "Enregistré", "da-DK": "Registreret", "cs-CZ": "Zaznamenáno", "ar-EG": "مسجَّل", "zh-CN": "已记录", "zh-TW": "已登記"},
  "Recorded by": {"de-DE": "Erfasst von", "fr-FR": "Enregistré par", "da-DK": "Registreret af", "cs-CZ": "Zaznamenal", "ar-EG": "سجّله", "zh-CN": "记录人", "zh-TW": "登記人"},
  "Records": {"de-DE": "Daten", "fr-FR": "Registres", "da-DK": "Registreringer", "cs-CZ": "Záznamy", "ar-EG": "السجلات", "zh-CN": "记录", "zh-TW": "紀錄"},
  "Refund": {"de-DE": "Erstattung", "fr-FR": "Remboursement", "da-DK": "Refusion", "cs-CZ": "Vrácení peněz", "ar-EG": "استرداد", "zh-CN": "退款", "zh-TW": "退款"},
  "Refund asked": {"de-DE": "Erstattung angefragt", "fr-FR": "Remboursement demandé", "da-DK": "Refusion ønsket", "cs-CZ": "Žádost o vrácení peněz", "ar-EG": "طُلب الاسترداد", "zh-CN": "已申请退款", "zh-TW": "已申請退款"},
  "Refund declined": {"de-DE": "Erstattung abgelehnt", "fr-FR": "Remboursement refusé", "da-DK": "Refusion afvist", "cs-CZ": "Vrácení peněz zamítnuto", "ar-EG": "رُفض الاسترداد", "zh-CN": "退款被拒", "zh-TW": "退款未通過"},
  "Refund recorded": {"de-DE": "Erstattung erfasst", "fr-FR": "Remboursement enregistré", "da-DK": "Refusion registreret", "cs-CZ": "Vrácení peněz zaznamenáno", "ar-EG": "سُجّل الاسترداد", "zh-CN": "退款已记录", "zh-TW": "退款已登記"},
  "Refund request declined": {"de-DE": "Erstattungsanfrage abgelehnt", "fr-FR": "Demande de remboursement refusée", "da-DK": "Anmodning om refusion afvist", "cs-CZ": "Žádost o vrácení peněz zamítnuta", "ar-EG": "رُفض طلب الاسترداد", "zh-CN": "退款申请未通过", "zh-TW": "退款申請未通過"},
  "Refund words": {"de-DE": "Text zur Erstattung", "fr-FR": "Texte sur les remboursements", "da-DK": "Tekst om refusion", "cs-CZ": "Text o vrácení peněz", "ar-EG": "نص الاسترداد", "zh-CN": "退款说明", "zh-TW": "退款說明文字"},
  "Refunded": {"de-DE": "Erstattet", "fr-FR": "Remboursé", "da-DK": "Refunderet", "cs-CZ": "Vráceno", "ar-EG": "مُسترد", "zh-CN": "已退款", "zh-TW": "已退款"},
  "Refunds": {"de-DE": "Erstattungen", "fr-FR": "Remboursements", "da-DK": "Refusioner", "cs-CZ": "Vrácení peněz", "ar-EG": "المبالغ المستردة", "zh-CN": "退款", "zh-TW": "退款"},
  "Refunds close this many days before a show": {"de-DE": "Erstattungen enden so viele Tage vor der Show", "fr-FR": "Fin des remboursements, en jours avant le spectacle", "da-DK": "Refusion lukker så mange dage før et arrangement", "cs-CZ": "Vrácení peněz končí tolik dní před akcí", "ar-EG": "يُغلق الاسترداد قبل الحفل بهذه المدة بالأيام", "zh-CN": "演出前多少天停止退款", "zh-TW": "演出前幾天停止退款"},
  "Refunds until": {"de-DE": "Erstattung bis", "fr-FR": "Remboursable jusqu'au", "da-DK": "Refusion indtil", "cs-CZ": "Vrácení peněz do", "ar-EG": "الاسترداد متاح حتى", "zh-CN": "可退款至", "zh-TW": "退款期限"},
  "Register": {"de-DE": "Anmeldung", "fr-FR": "Inscription", "da-DK": "Tilmelding", "cs-CZ": "Registrace", "ar-EG": "تسجيل", "zh-CN": "报名", "zh-TW": "報名"},
  "Released": {"de-DE": "Zurückgegeben", "fr-FR": "Remis en vente", "da-DK": "Frigivet", "cs-CZ": "Uvolněno", "ar-EG": "أُعيدت إلى البيع", "zh-CN": "已释放", "zh-TW": "已釋出"},
  "Remind the evening before": {"de-DE": "Am Vorabend erinnern", "fr-FR": "Rappel la veille au soir", "da-DK": "Påmind aftenen før", "cs-CZ": "Připomenout večer předem", "ar-EG": "التذكير في المساء السابق", "zh-CN": "前一晚提醒", "zh-TW": "前一晚提醒"},
  "Reminder": {"de-DE": "Erinnerung", "fr-FR": "Rappel", "da-DK": "Påmindelse", "cs-CZ": "Připomínka", "ar-EG": "تذكير", "zh-CN": "提醒", "zh-TW": "提醒"},
  "Reminder: your transfer": {"de-DE": "Erinnerung: deine Überweisung", "fr-FR": "Rappel : votre virement", "da-DK": "Påmindelse: din overførsel", "cs-CZ": "Připomínka: váš převod", "ar-EG": "تذكير: تحويلك", "zh-CN": "提醒：你的转账", "zh-TW": "提醒：你的轉帳"},
  "Reminders": {"de-DE": "Erinnerungen", "fr-FR": "Rappels", "da-DK": "Påmindelser", "cs-CZ": "Připomínky", "ar-EG": "التذكيرات", "zh-CN": "提醒", "zh-TW": "提醒"},
  "Removed": {"de-DE": "Entfernt", "fr-FR": "Retiré", "da-DK": "Fjernet", "cs-CZ": "Odebráno", "ar-EG": "أُزيل", "zh-CN": "已移除", "zh-TW": "已移除"},
  "Retry key": {"de-DE": "Wiederholungsschlüssel", "fr-FR": "Clé de relance", "da-DK": "Genforsøgsnøgle", "cs-CZ": "Klíč pro opakování", "ar-EG": "مفتاح إعادة المحاولة", "zh-CN": "重试码", "zh-TW": "重試碼"},
  "Right show": {"de-DE": "Richtige Show", "fr-FR": "Bon spectacle", "da-DK": "Rigtigt arrangement", "cs-CZ": "Správná akce", "ar-EG": "الحفل الصحيح", "zh-CN": "场次正确", "zh-TW": "場次正確"},
  "Room": {"de-DE": "Raum", "fr-FR": "Salle", "da-DK": "Sal", "cs-CZ": "Sál", "ar-EG": "القاعة", "zh-CN": "演出厅", "zh-TW": "廳"},
  "Room capacity": {"de-DE": "Kapazität des Raums", "fr-FR": "Jauge de la salle", "da-DK": "Salens kapacitet", "cs-CZ": "Kapacita sálu", "ar-EG": "سعة القاعة", "zh-CN": "演出厅容量", "zh-TW": "廳容納人數"},
  "Rooms": {"de-DE": "Räume", "fr-FR": "Salles", "da-DK": "Sale", "cs-CZ": "Sály", "ar-EG": "القاعات", "zh-CN": "演出厅", "zh-TW": "表演廳"},
  "See you tomorrow": {"de-DE": "Bis morgen", "fr-FR": "À demain", "da-DK": "Vi ses i morgen", "cs-CZ": "Uvidíme se zítra", "ar-EG": "نراك غدا", "zh-CN": "明天见", "zh-TW": "明天見"},
  "See you tomorrow (a friend's ticket)": {"de-DE": "Bis morgen (Ticket von Freunden)", "fr-FR": "À demain (billet d'un proche)", "da-DK": "Vi ses i morgen (en vens billet)", "cs-CZ": "Uvidíme se zítra (vstupenka od kamaráda)", "ar-EG": "نراك غدا (تذكرة من صديق)", "zh-CN": "明天见（朋友送的票）", "zh-TW": "明天見（朋友送的票）"},
  "See you tonight": {"de-DE": "Bis heute Abend", "fr-FR": "À ce soir", "da-DK": "Vi ses i aften", "cs-CZ": "Uvidíme se dnes večer", "ar-EG": "نراك الليلة", "zh-CN": "今晚见", "zh-TW": "今晚見"},
  "See you tonight (a friend's ticket)": {"de-DE": "Bis heute Abend (Ticket von Freunden)", "fr-FR": "À ce soir (billet d'un proche)", "da-DK": "Vi ses i aften (en vens billet)", "cs-CZ": "Uvidíme se dnes večer (vstupenka od kamaráda)", "ar-EG": "نراك الليلة (تذكرة من صديق)", "zh-CN": "今晚见（朋友送的票）", "zh-TW": "今晚見（朋友送的票）"},
  "Selling": {"de-DE": "Verkauf aktiv", "fr-FR": "Ventes ouvertes", "da-DK": "Sælger", "cs-CZ": "Prodává se", "ar-EG": "قيد البيع", "zh-CN": "在售", "zh-TW": "販售中"},
  "Send \"See you tonight\"": {"de-DE": "„Bis heute Abend“ senden", "fr-FR": "Envoyer « À ce soir »", "da-DK": "Send »Vi ses i aften«", "cs-CZ": "Poslat „Uvidíme se dnes večer“", "ar-EG": "إرسال «نراك الليلة»", "zh-CN": "发送“今晚见”", "zh-TW": "寄送「今晚見」"},
  "Send a receipt with an order paid in full, and let the buyer open it from their order.": {"de-DE": "Bei voll bezahlten Bestellungen eine Quittung mitschicken, die man auch in der Bestellung öffnen kann.", "fr-FR": "Envoyer un reçu avec chaque commande payée intégralement, et permettre à l'acheteur de l'ouvrir depuis sa commande.", "da-DK": "Send en kvittering med en fuldt betalt ordre, og lad køberen åbne den fra sin ordre.", "cs-CZ": "Poslat účtenku k plně zaplacené objednávce a nechat kupujícího otevřít ji ze své objednávky.", "ar-EG": "أرسل إيصالا مع كل طلب مدفوع بالكامل، ودع المشتري يفتحه من طلبه.", "zh-CN": "订单全额付清后发送收据，购票人也可在订单中查看。", "zh-TW": "訂單全額付清時寄送收據，購票人也能從訂單頁面開啟。"},
  "Send a ticket to a friend": {"de-DE": "Ein Ticket weitergeben", "fr-FR": "Envoyer un billet à un proche", "da-DK": "Send en billet til en ven", "cs-CZ": "Poslat vstupenku kamarádovi", "ar-EG": "أرسل تذكرة إلى صديق", "zh-CN": "把票送给朋友", "zh-TW": "把票送給朋友"},
  "Sent": {"de-DE": "Gesendet", "fr-FR": "Envoyé", "da-DK": "Sendt", "cs-CZ": "Odesláno", "ar-EG": "أُرسلت", "zh-CN": "已发送", "zh-TW": "已寄出"},
  "Sent by": {"de-DE": "Gesendet von", "fr-FR": "Envoyé par", "da-DK": "Sendt af", "cs-CZ": "Odeslal", "ar-EG": "أرسلها", "zh-CN": "发送人", "zh-TW": "寄件人"},
  "Sent to": {"de-DE": "Gesendet an", "fr-FR": "Envoyé à", "da-DK": "Sendt til", "cs-CZ": "Příjemce", "ar-EG": "أُرسلت إلى", "zh-CN": "发送至", "zh-TW": "收件人"},
  "Sent to a friend": {"de-DE": "Weitergegeben", "fr-FR": "Envoyé à un proche", "da-DK": "Sendt til en ven", "cs-CZ": "Posláno kamarádovi", "ar-EG": "أُرسلت إلى صديق", "zh-CN": "已送给朋友", "zh-TW": "已送給朋友"},
  "Sent to email": {"de-DE": "Gesendet an E-Mail", "fr-FR": "Envoyé à l'adresse", "da-DK": "Sendt til mail", "cs-CZ": "Odesláno na e-mail", "ar-EG": "أُرسلت إلى البريد", "zh-CN": "发送到的邮箱", "zh-TW": "寄送信箱"},
  "Set times are up": {"de-DE": "Spielzeiten stehen", "fr-FR": "Horaires de passage publiés", "da-DK": "Spilletiderne er lagt op", "cs-CZ": "Časy vystoupení jsou zveřejněné", "ar-EG": "مواعيد الفقرات منشورة", "zh-CN": "演出时间表已公布", "zh-TW": "演出時間表已公布"},
  "Settings": {"de-DE": "Einstellungen", "fr-FR": "Réglages", "da-DK": "Indstillinger", "cs-CZ": "Nastavení", "ar-EG": "الإعدادات", "zh-CN": "设置", "zh-TW": "設定"},
  "Short name": {"de-DE": "Kurzname", "fr-FR": "Nom court", "da-DK": "Kort navn", "cs-CZ": "Krátký název", "ar-EG": "الاسم المختصر", "zh-CN": "简称", "zh-TW": "簡稱"},
  "Show": {"de-DE": "Show", "fr-FR": "Spectacle", "da-DK": "Arrangement", "cs-CZ": "Akce", "ar-EG": "الحفل", "zh-CN": "演出", "zh-TW": "演出"},
  "Show day": {"de-DE": "Showtag", "fr-FR": "Jour du spectacle", "da-DK": "Arrangementsdag", "cs-CZ": "Den akce", "ar-EG": "يوم الحفل", "zh-CN": "演出日", "zh-TW": "演出日"},
  "Show days": {"de-DE": "Showtage", "fr-FR": "Jours du spectacle", "da-DK": "Arrangementsdage", "cs-CZ": "Dny akce", "ar-EG": "أيام الحفل", "zh-CN": "演出日", "zh-TW": "演出日"},
  "Show ends": {"de-DE": "Show endet", "fr-FR": "Fin du spectacle", "da-DK": "Arrangementet slutter", "cs-CZ": "Konec akce", "ar-EG": "نهاية الحفل", "zh-CN": "演出结束", "zh-TW": "演出結束"},
  "Shows": {"de-DE": "Shows", "fr-FR": "Spectacles", "da-DK": "Arrangementer", "cs-CZ": "Akce", "ar-EG": "الحفلات", "zh-CN": "演出", "zh-TW": "演出"},
  "Sign in and My tickets": {"de-DE": "Anmelden und Meine Tickets", "fr-FR": "Connexion et Mes billets", "da-DK": "Log ind og Mine billetter", "cs-CZ": "Přihlášení a Moje vstupenky", "ar-EG": "تسجيل الدخول وتذاكري", "zh-CN": "登录与“我的票”", "zh-TW": "登入與我的票券"},
  "Skipped": {"de-DE": "Übersprungen", "fr-FR": "Ignoré", "da-DK": "Sprunget over", "cs-CZ": "Přeskočeno", "ar-EG": "تم تخطيها", "zh-CN": "已跳过", "zh-TW": "已略過"},
  "Skipped by hand": {"de-DE": "Von Hand übersprungen", "fr-FR": "Ignoré à la main", "da-DK": "Sprunget over manuelt", "cs-CZ": "Přeskočeno ručně", "ar-EG": "تم تخطيها يدويا", "zh-CN": "手动跳过", "zh-TW": "手動略過"},
  "Something else": {"de-DE": "Etwas anderes", "fr-FR": "Autre chose", "da-DK": "Noget andet", "cs-CZ": "Něco jiného", "ar-EG": "شيء آخر", "zh-CN": "其他原因", "zh-TW": "其他原因"},
  "Sort code or routing number": {"de-DE": "BIC oder Bankleitzahl", "fr-FR": "Code banque ou BIC", "da-DK": "Reg.nr. eller routingnummer", "cs-CZ": "Kód banky", "ar-EG": "رمز الفرع أو رقم التوجيه", "zh-CN": "银行代码", "zh-TW": "銀行代碼"},
  "Standard": {"de-DE": "Standard", "fr-FR": "Standard", "da-DK": "Standard", "cs-CZ": "Standardní", "ar-EG": "عادية", "zh-CN": "标准", "zh-TW": "一般"},
  "State": {"de-DE": "Zustand", "fr-FR": "État", "da-DK": "Tilstand", "cs-CZ": "Stav", "ar-EG": "الحالة", "zh-CN": "状态", "zh-TW": "狀態"},
  "Status": {"de-DE": "Status", "fr-FR": "Statut", "da-DK": "Status", "cs-CZ": "Status", "ar-EG": "الوضع", "zh-CN": "状态", "zh-TW": "狀態"},
  "Subject": {"de-DE": "Betreff", "fr-FR": "Objet", "da-DK": "Emne", "cs-CZ": "Předmět", "ar-EG": "الموضوع", "zh-CN": "主题", "zh-TW": "主旨"},
  "Subject as sent": {"de-DE": "Betreff wie gesendet", "fr-FR": "Objet tel qu'envoyé", "da-DK": "Emne som sendt", "cs-CZ": "Předmět, jak byl odeslán", "ar-EG": "الموضوع كما أُرسل", "zh-CN": "主题原文", "zh-TW": "寄出的主旨"},
  "Taken": {"de-DE": "Eingenommen", "fr-FR": "Pris", "da-DK": "Taget", "cs-CZ": "Vybráno", "ar-EG": "محصَّل", "zh-CN": "已收取", "zh-TW": "已收取"},
  "Taken at the door": {"de-DE": "Am Einlass eingenommen", "fr-FR": "Encaissé à l'entrée", "da-DK": "Modtaget ved døren", "cs-CZ": "Vybráno u vchodu", "ar-EG": "حُصّل عند الباب", "zh-CN": "门口收取", "zh-TW": "現場收取"},
  "Taken by": {"de-DE": "Kassiert von", "fr-FR": "Encaissé par", "da-DK": "Modtaget af", "cs-CZ": "Vybral", "ar-EG": "حصّله", "zh-CN": "收款人", "zh-TW": "收款人"},
  "Taken off the total": {"de-DE": "Vom Gesamtbetrag abgezogen", "fr-FR": "Déduit du total", "da-DK": "Trukket fra totalen", "cs-CZ": "Odečteno z celkové částky", "ar-EG": "خُصم من الإجمالي", "zh-CN": "从总额中扣除", "zh-TW": "從總額扣除"},
  "Talk": {"de-DE": "Vortrag", "fr-FR": "Rencontre", "da-DK": "Foredrag", "cs-CZ": "Beseda", "ar-EG": "ندوة", "zh-CN": "讲座", "zh-TW": "講座"},
  "The box office cancelled it": {"de-DE": "Von der Kasse storniert", "fr-FR": "Annulé par la billetterie", "da-DK": "Billetlugen annullerede den", "cs-CZ": "Zrušila ji pokladna", "ar-EG": "ألغاه شباك التذاكر", "zh-CN": "售票处已取消", "zh-TW": "售票處已取消"},
  "The buyer cancelled it": {"de-DE": "Vom Käufer storniert", "fr-FR": "Annulé par l'acheteur", "da-DK": "Køberen annullerede den", "cs-CZ": "Zrušil ji kupující", "ar-EG": "ألغاه المشتري", "zh-CN": "购票人已取消", "zh-TW": "購票人已取消"},
  "The evening before": {"de-DE": "Am Vorabend", "fr-FR": "La veille au soir", "da-DK": "Aftenen før", "cs-CZ": "Večer předem", "ar-EG": "في المساء السابق", "zh-CN": "前一晚", "zh-TW": "前一晚"},
  "The show was cancelled": {"de-DE": "Die Show fällt aus", "fr-FR": "Le spectacle a été annulé", "da-DK": "Arrangementet blev aflyst", "cs-CZ": "Akce byla zrušena", "ar-EG": "أُلغي الحفل", "zh-CN": "演出已取消", "zh-TW": "演出已取消"},
  "The venue day starts at": {"de-DE": "Der Veranstaltungstag beginnt um", "fr-FR": "La journée de la salle commence à", "da-DK": "Spillestedets dag starter kl.", "cs-CZ": "Provozní den klubu začíná v", "ar-EG": "يبدأ يوم المكان في", "zh-CN": "场馆营业日开始于", "zh-TW": "場館營業日起算時間"},
  "Ticket": {"de-DE": "Ticket", "fr-FR": "Billet", "da-DK": "Billet", "cs-CZ": "Vstupenka", "ar-EG": "التذكرة", "zh-CN": "门票", "zh-TW": "票券"},
  "Ticket code": {"de-DE": "Ticketcode", "fr-FR": "Code du billet", "da-DK": "Billetkode", "cs-CZ": "Kód vstupenky", "ar-EG": "رمز التذكرة", "zh-CN": "票码", "zh-TW": "票券代碼"},
  "Ticket type": {"de-DE": "Ticketart", "fr-FR": "Type de billet", "da-DK": "Billettype", "cs-CZ": "Typ vstupenky", "ar-EG": "نوع التذكرة", "zh-CN": "票种", "zh-TW": "票種"},
  "Ticket types": {"de-DE": "Ticketarten", "fr-FR": "Types de billets", "da-DK": "Billettyper", "cs-CZ": "Typy vstupenek", "ar-EG": "أنواع التذاكر", "zh-CN": "票种", "zh-TW": "票種"},
  "Ticket's show": {"de-DE": "Show des Tickets", "fr-FR": "Spectacle du billet", "da-DK": "Billettens arrangement", "cs-CZ": "Akce vstupenky", "ar-EG": "حفل التذكرة", "zh-CN": "门票对应的演出", "zh-TW": "票券的演出"},
  "Ticket's show number": {"de-DE": "Shownummer des Tickets", "fr-FR": "Numéro du spectacle du billet", "da-DK": "Billettens arrangementsnummer", "cs-CZ": "Číslo akce vstupenky", "ar-EG": "رقم حفل التذكرة", "zh-CN": "门票对应的演出编号", "zh-TW": "票券的演出編號"},
  "Tickets": {"de-DE": "Tickets", "fr-FR": "Billets", "da-DK": "Billetter", "cs-CZ": "Vstupenky", "ar-EG": "التذاكر", "zh-CN": "门票", "zh-TW": "票券"},
  "Tickets are back": {"de-DE": "Es gibt wieder Tickets", "fr-FR": "Des billets sont revenus", "da-DK": "Billetterne er tilbage", "cs-CZ": "Vstupenky jsou zpět", "ar-EG": "عادت التذاكر", "zh-CN": "又有票了", "zh-TW": "有票釋出了"},
  "Tickets cancelled": {"de-DE": "Tickets storniert", "fr-FR": "Billets annulés", "da-DK": "Billetter annulleret", "cs-CZ": "Vstupenky zrušeny", "ar-EG": "أُلغيت التذاكر", "zh-CN": "门票已取消", "zh-TW": "票券已取消"},
  "Tickets sold": {"de-DE": "Verkaufte Tickets", "fr-FR": "Billets vendus", "da-DK": "Solgte billetter", "cs-CZ": "Prodané vstupenky", "ar-EG": "التذاكر المبيعة", "zh-CN": "已售门票", "zh-TW": "已售票數"},
  "Tickets that can't be paid at the door": {"de-DE": "Tickets ohne Zahlung am Einlass", "fr-FR": "Billets non payables à l'entrée", "da-DK": "Billetter der ikke kan betales ved døren", "cs-CZ": "Vstupenky, které nelze zaplatit u vchodu", "ar-EG": "تذاكر لا تُدفع عند الباب", "zh-CN": "不可门口付款的门票", "zh-TW": "不可現場付款的票"},
  "Tickets that can't be paid by transfer": {"de-DE": "Tickets ohne Zahlung per Überweisung", "fr-FR": "Billets non payables par virement", "da-DK": "Billetter der ikke kan betales via overførsel", "cs-CZ": "Vstupenky, které nelze zaplatit převodem", "ar-EG": "تذاكر لا تُدفع بالتحويل", "zh-CN": "不可转账付款的门票", "zh-TW": "不可轉帳付款的票"},
  "Times in": {"de-DE": "Einlässe", "fr-FR": "Entrées", "da-DK": "Gange inde", "cs-CZ": "Počet vstupů", "ar-EG": "مرات الدخول", "zh-CN": "入场次数", "zh-TW": "入場次數"},
  "To": {"de-DE": "An", "fr-FR": "À", "da-DK": "Til", "cs-CZ": "Komu", "ar-EG": "إلى", "zh-CN": "收件人", "zh-TW": "至"},
  "Total": {"de-DE": "Gesamt", "fr-FR": "Total", "da-DK": "I alt", "cs-CZ": "Celkem", "ar-EG": "الإجمالي", "zh-CN": "总计", "zh-TW": "總計"},
  "Transfer overdue": {"de-DE": "Überweisung überfällig", "fr-FR": "Virement en retard", "da-DK": "Overførsel forsinket", "cs-CZ": "Převod po splatnosti", "ar-EG": "تأخر التحويل", "zh-CN": "转账逾期", "zh-TW": "轉帳逾期"},
  "Transfers due by": {"de-DE": "Überweisungen fällig bis", "fr-FR": "Virements attendus avant le", "da-DK": "Overførsler forfalder senest", "cs-CZ": "Převody splatné do", "ar-EG": "آخر موعد للتحويلات", "zh-CN": "转账截止", "zh-TW": "轉帳期限"},
  "Transfers overdue": {"de-DE": "Überfällige Überweisungen", "fr-FR": "Virements en retard", "da-DK": "Forsinkede overførsler", "cs-CZ": "Převody po splatnosti", "ar-EG": "تحويلات متأخرة", "zh-CN": "逾期转账", "zh-TW": "逾期轉帳"},
  "Type": {"de-DE": "Typ", "fr-FR": "Type", "da-DK": "Type", "cs-CZ": "Typ", "ar-EG": "النوع", "zh-CN": "类型", "zh-TW": "類型"},
  "Types behind a code": {"de-DE": "Ticketarten hinter einem Code", "fr-FR": "Types réservés à un code", "da-DK": "Typer bag en kode", "cs-CZ": "Typy dostupné přes kód", "ar-EG": "أنواع تتطلب رمزا", "zh-CN": "凭代码购买的票种", "zh-TW": "需代碼的票種"},
  "Unlocks": {"de-DE": "Schaltet frei", "fr-FR": "Débloque", "da-DK": "Låser op for", "cs-CZ": "Odemyká", "ar-EG": "يفتح", "zh-CN": "解锁", "zh-TW": "解鎖"},
  "Unlocks a hidden ticket type": {"de-DE": "Schaltet eine versteckte Ticketart frei", "fr-FR": "Débloque un type de billet caché", "da-DK": "Låser op for en skjult billettype", "cs-CZ": "Odemyká skrytý typ vstupenky", "ar-EG": "يفتح نوع تذكرة مخفيا", "zh-CN": "解锁隐藏票种", "zh-TW": "解鎖隱藏票種"},
  "Uses at most": {"de-DE": "Höchstens einlösbar", "fr-FR": "Utilisations au maximum", "da-DK": "Maks. antal anvendelser", "cs-CZ": "Nejvýše použití", "ar-EG": "الحد الأقصى للاستخدام", "zh-CN": "最多使用次数", "zh-TW": "使用次數上限"},
  "Valid": {"de-DE": "Gültig", "fr-FR": "Valable", "da-DK": "Gyldig", "cs-CZ": "Platné", "ar-EG": "صالحة", "zh-CN": "有效", "zh-TW": "有效"},
  "Valid until": {"de-DE": "Gültig bis", "fr-FR": "Valable jusqu'au", "da-DK": "Gyldig til", "cs-CZ": "Platné do", "ar-EG": "صالحة حتى", "zh-CN": "有效期至", "zh-TW": "有效期限"},
  "Venue name": {"de-DE": "Name der Location", "fr-FR": "Nom de la salle", "da-DK": "Spillestedets navn", "cs-CZ": "Název klubu", "ar-EG": "اسم المكان", "zh-CN": "场馆名称", "zh-TW": "場館名稱"},
  "Venue settings": {"de-DE": "Einstellungen der Location", "fr-FR": "Réglages de la salle", "da-DK": "Indstillinger for spillestedet", "cs-CZ": "Nastavení klubu", "ar-EG": "إعدادات المكان", "zh-CN": "场馆设置", "zh-TW": "場館設定"},
  "Void": {"de-DE": "Ungültig", "fr-FR": "Invalider", "da-DK": "Ugyldig", "cs-CZ": "Neplatné", "ar-EG": "إبطال", "zh-CN": "作废", "zh-TW": "作廢"},
  "Voided": {"de-DE": "Annulliert", "fr-FR": "Invalidé", "da-DK": "Ugyldiggjort", "cs-CZ": "Zneplatněno", "ar-EG": "أُبطلت", "zh-CN": "已作废", "zh-TW": "已作廢"},
  "Voided by": {"de-DE": "Annulliert von", "fr-FR": "Invalidé par", "da-DK": "Ugyldiggjort af", "cs-CZ": "Zneplatnil", "ar-EG": "أبطلها", "zh-CN": "作废人", "zh-TW": "作廢人"},
  "Voided on": {"de-DE": "Annulliert am", "fr-FR": "Invalidé le", "da-DK": "Ugyldiggjort den", "cs-CZ": "Zneplatněno dne", "ar-EG": "تاريخ الإبطال", "zh-CN": "作废时间", "zh-TW": "作廢日期"},
  "Waiting": {"de-DE": "Wartet", "fr-FR": "En attente", "da-DK": "Venter", "cs-CZ": "Čeká", "ar-EG": "في الانتظار", "zh-CN": "等待中", "zh-TW": "等待中"},
  "Waiting for your transfer": {"de-DE": "Wir warten auf deine Überweisung", "fr-FR": "En attente de votre virement", "da-DK": "Venter på din overførsel", "cs-CZ": "Čekáme na váš převod", "ar-EG": "بانتظار تحويلك", "zh-CN": "等待你的转账", "zh-TW": "等待你的轉帳"},
  "Waiting to be sent": {"de-DE": "Wartet auf Versand", "fr-FR": "En attente d'envoi", "da-DK": "Venter på at blive sendt", "cs-CZ": "Čeká na odeslání", "ar-EG": "بانتظار الإرسال", "zh-CN": "待发送", "zh-TW": "等待寄出"},
  "Waitlist place": {"de-DE": "Wartelistenplatz", "fr-FR": "Place en liste d'attente", "da-DK": "Plads på ventelisten", "cs-CZ": "Místo v čekací listině", "ar-EG": "مكان في قائمة الانتظار", "zh-CN": "候补排位", "zh-TW": "候補順位"},
  "Waitlist when sold out": {"de-DE": "Warteliste bei Ausverkauf", "fr-FR": "Liste d'attente si complet", "da-DK": "Venteliste ved udsolgt", "cs-CZ": "Čekací listina po vyprodání", "ar-EG": "قائمة انتظار عند نفاد التذاكر", "zh-CN": "售罄后开放候补", "zh-TW": "售完後開放候補"},
  "Waitlists": {"de-DE": "Wartelisten", "fr-FR": "Listes d'attente", "da-DK": "Ventelister", "cs-CZ": "Čekací listiny", "ar-EG": "قوائم الانتظار", "zh-CN": "候补名单", "zh-TW": "候補名單"},
  "Was on": {"de-DE": "Früherer Termin", "fr-FR": "Prévu initialement le", "da-DK": "Var den", "cs-CZ": "Původně dne", "ar-EG": "كان موعده", "zh-CN": "原定日期", "zh-TW": "原訂日期"},
  "Weekend pass": {"de-DE": "Wochenendpass", "fr-FR": "Pass week-end", "da-DK": "Weekendpas", "cs-CZ": "Víkendová vstupenka", "ar-EG": "تصريح عطلة نهاية الأسبوع", "zh-CN": "周末通票", "zh-TW": "週末通行證"},
  "What it does": {"de-DE": "Wirkung", "fr-FR": "Ce qu'il fait", "da-DK": "Hvad den gør", "cs-CZ": "Co dělá", "ar-EG": "ما يفعله", "zh-CN": "作用", "zh-TW": "用途"},
  "What it is for": {"de-DE": "Wofür", "fr-FR": "À quoi il sert", "da-DK": "Hvad den er til", "cs-CZ": "K čemu slouží", "ar-EG": "الغرض منه", "zh-CN": "用途", "zh-TW": "用途說明"},
  "What went wrong": {"de-DE": "Was schiefging", "fr-FR": "Ce qui n'a pas marché", "da-DK": "Hvad gik galt", "cs-CZ": "Co se pokazilo", "ar-EG": "ما الخطأ الذي حدث", "zh-CN": "出了什么问题", "zh-TW": "問題說明"},
  "When money goes back": {"de-DE": "Wann das Geld zurückkommt", "fr-FR": "Délai de remboursement", "da-DK": "Hvornår pengene betales tilbage", "cs-CZ": "Kdy se peníze vracejí", "ar-EG": "موعد رد المال", "zh-CN": "退款到账时间", "zh-TW": "退款時間"},
  "Which send": {"de-DE": "Welcher Versand", "fr-FR": "Envoi concerné", "da-DK": "Hvilken afsendelse", "cs-CZ": "Které odeslání", "ar-EG": "أي إرسال", "zh-CN": "对应的发送", "zh-TW": "對應的寄送"},
  "Who can buy": {"de-DE": "Wer kaufen kann", "fr-FR": "Qui peut acheter", "da-DK": "Hvem kan købe", "cs-CZ": "Kdo může koupit", "ar-EG": "من يمكنه الشراء", "zh-CN": "购买资格", "zh-TW": "購票資格"},
  "Why it was cancelled": {"de-DE": "Grund der Stornierung", "fr-FR": "Motif de l'annulation", "da-DK": "Hvorfor den blev annulleret", "cs-CZ": "Proč bylo zrušeno", "ar-EG": "سبب الإلغاء", "zh-CN": "取消原因", "zh-TW": "取消原因"},
  "Why it was skipped": {"de-DE": "Grund fürs Überspringen", "fr-FR": "Pourquoi il a été ignoré", "da-DK": "Hvorfor den blev sprunget over", "cs-CZ": "Proč bylo přeskočeno", "ar-EG": "سبب التخطي", "zh-CN": "跳过原因", "zh-TW": "略過原因"},
  "Why the order was cancelled": {"de-DE": "Warum die Bestellung storniert wurde", "fr-FR": "Motif de l'annulation de la commande", "da-DK": "Hvorfor ordren blev annulleret", "cs-CZ": "Proč byla objednávka zrušena", "ar-EG": "سبب إلغاء الطلب", "zh-CN": "订单取消原因", "zh-TW": "訂單取消原因"},
  "With": {"de-DE": "Support", "fr-FR": "Avec", "da-DK": "Med", "cs-CZ": "Spolu s", "ar-EG": "مع", "zh-CN": "附带", "zh-TW": "搭配"},
  "With a code": {"de-DE": "Mit Code", "fr-FR": "Avec un code", "da-DK": "Med en kode", "cs-CZ": "S kódem", "ar-EG": "برمز", "zh-CN": "凭代码", "zh-TW": "需輸入代碼"},
  "Words": {"de-DE": "Text", "fr-FR": "Textes", "da-DK": "Tekster", "cs-CZ": "Texty", "ar-EG": "النصوص", "zh-CN": "文字", "zh-TW": "文字"},
  "Yes or no": {"de-DE": "Ja oder nein", "fr-FR": "Oui ou non", "da-DK": "Ja eller nej", "cs-CZ": "Ano, nebo ne", "ar-EG": "نعم أو لا", "zh-CN": "是或否", "zh-TW": "是或否"},
  "Your show has moved": {"de-DE": "Deine Show wurde verlegt", "fr-FR": "Votre spectacle change de date", "da-DK": "Dit arrangement er flyttet", "cs-CZ": "Vaše akce se přesouvá", "ar-EG": "تغيّر موعد حفلك", "zh-CN": "你的演出已改期", "zh-TW": "你的演出已改期"},
  "Your show has moved (a friend's ticket)": {"de-DE": "Deine Show wurde verlegt (Ticket von Freunden)", "fr-FR": "Votre spectacle change de date (billet d'un proche)", "da-DK": "Dit arrangement er flyttet (en vens billet)", "cs-CZ": "Vaše akce se přesouvá (vstupenka od kamaráda)", "ar-EG": "تغيّر موعد حفلك (تذكرة من صديق)", "zh-CN": "你的演出已改期（朋友送的票）", "zh-TW": "你的演出已改期（朋友送的票）"},
  "Your show is cancelled (a friend's ticket)": {"de-DE": "Deine Show fällt aus (Ticket von Freunden)", "fr-FR": "Votre spectacle est annulé (billet d'un proche)", "da-DK": "Dit arrangement er aflyst (en vens billet)", "cs-CZ": "Vaše akce je zrušená (vstupenka od kamaráda)", "ar-EG": "أُلغي حفلك (تذكرة من صديق)", "zh-CN": "你的演出已取消（朋友送的票）", "zh-TW": "你的演出已取消（朋友送的票）"},
  "Your show is cancelled (nothing paid)": {"de-DE": "Deine Show fällt aus (nichts bezahlt)", "fr-FR": "Votre spectacle est annulé (rien de payé)", "da-DK": "Dit arrangement er aflyst (intet betalt)", "cs-CZ": "Vaše akce je zrušená (nic nezaplaceno)", "ar-EG": "أُلغي حفلك (لم يُدفع شيء)", "zh-CN": "你的演出已取消（未付款）", "zh-TW": "你的演出已取消（未付款）"},
  "Your show is cancelled (paid)": {"de-DE": "Deine Show fällt aus (bezahlt)", "fr-FR": "Votre spectacle est annulé (déjà payé)", "da-DK": "Dit arrangement er aflyst (betalt)", "cs-CZ": "Vaše akce je zrušená (zaplaceno)", "ar-EG": "أُلغي حفلك (مدفوع)", "zh-CN": "你的演出已取消（已付款）", "zh-TW": "你的演出已取消（已付款）"},
  "Your ticket came back": {"de-DE": "Dein Ticket ist zurück", "fr-FR": "Votre billet vous est revenu", "da-DK": "Din billet kom tilbage", "cs-CZ": "Vstupenka se vám vrátila", "ar-EG": "عادت إليك تذكرتك", "zh-CN": "你的票已退回", "zh-TW": "你的票退回了"},
  "Your ticket is ready": {"de-DE": "Dein Ticket ist da", "fr-FR": "Votre billet est prêt", "da-DK": "Din billet er klar", "cs-CZ": "Vaše vstupenka je připravená", "ar-EG": "تذكرتك جاهزة", "zh-CN": "你的票已准备好", "zh-TW": "你的票準備好了"},
  "Your tickets": {"de-DE": "Deine Tickets", "fr-FR": "Vos billets", "da-DK": "Dine billetter", "cs-CZ": "Vaše vstupenky", "ar-EG": "تذاكرك", "zh-CN": "你的门票", "zh-TW": "你的票券"},
  "Your tickets (paid at the box office)": {"de-DE": "Deine Tickets (an der Kasse bezahlt)", "fr-FR": "Vos billets (payés à la billetterie)", "da-DK": "Dine billetter (betalt i billetlugen)", "cs-CZ": "Vaše vstupenky (zaplaceno v pokladně)", "ar-EG": "تذاكرك (مدفوعة في شباك التذاكر)", "zh-CN": "你的门票（已在售票处付款）", "zh-TW": "你的票券（已在售票處付款）"},
  "Your tickets went back on sale": {"de-DE": "Deine Tickets sind wieder im Verkauf", "fr-FR": "Vos billets ont été remis en vente", "da-DK": "Dine billetter kom til salg igen", "cs-CZ": "Vaše vstupenky se vrátily do prodeje", "ar-EG": "عادت تذاكرك إلى البيع", "zh-CN": "你的门票已重新开售", "zh-TW": "你的票已重新開賣"},
};
