/**
 * The icons the screens draw, by their Lucide names. Named imports, so only these ship; a name the
 * screens do not know draws a plain circle.
 */
import {
  Accessibility,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  BadgePercent,
  Ban,
  Banknote,
  CameraOff,
  CircleCheckBig,
  Bell,
  Bike,
  Bus,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  CalendarX,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CirclePause,
  CircleX,
  ClipboardPaste,
  Clock,
  CloudOff,
  Copy,
  CreditCard,
  Disc,
  DoorOpen,
  Download,
  Ellipsis,
  Eye,
  FastForward,
  FileDown,
  Forward,
  Gauge,
  Gift,
  History,
  Hourglass,
  House,
  IdCard,
  Info,
  Key,
  KeyRound,
  Landmark,
  Link,
  List,
  ListChecks,
  ListOrdered,
  ListPlus,
  ListX,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailOpen,
  MapPin,
  Maximize2,
  Minus,
  Monitor,
  MonitorOff,
  Moon,
  Navigation,
  OctagonAlert,
  PartyPopper,
  PenLine,
  Plus,
  QrCode,
  ReceiptText,
  RefreshCw,
  Repeat,
  RotateCcw,
  RotateCw,
  ScanLine,
  Search,
  Send,
  Settings,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  Shuffle,
  Smartphone,
  SquarePen,
  Star,
  StickyNote,
  Store,
  Sun,
  Tent,
  Ticket,
  TicketCheck,
  TicketPercent,
  TicketX,
  Timer,
  TimerOff,
  Trash2,
  TriangleAlert,
  Undo2,
  Unplug,
  Upload,
  UserMinus,
  UserPen,
  UserPlus,
  UserRound,
  UserX,
  Users,
  Wallet,
  WandSparkles,
  Wifi,
  WifiOff,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "accessibility": Accessibility,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "badge-check": BadgeCheck,
  "badge-percent": BadgePercent,
  "ban": Ban,
  "banknote": Banknote,
  "bell": Bell,
  "bike": Bike,
  "bus": Bus,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "calendar-plus": CalendarPlus,
  "calendar-range": CalendarRange,
  "calendar-x": CalendarX,
  "chart-line": ChartLine,
  "check": Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle": Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-check-big": CircleCheckBig,
  "camera-off": CameraOff,
  "circle-dot": CircleDot,
  "circle-pause": CirclePause,
  "circle-x": CircleX,
  "clipboard-paste": ClipboardPaste,
  "clock": Clock,
  "cloud-off": CloudOff,
  "copy": Copy,
  "credit-card": CreditCard,
  "disc": Disc,
  "door-open": DoorOpen,
  "download": Download,
  "ellipsis": Ellipsis,
  "eye": Eye,
  "fast-forward": FastForward,
  "file-down": FileDown,
  "forward": Forward,
  "gauge": Gauge,
  "gift": Gift,
  "history": History,
  "hourglass": Hourglass,
  "house": House,
  "id-card": IdCard,
  "info": Info,
  "key": Key,
  "key-round": KeyRound,
  "landmark": Landmark,
  "link": Link,
  "list": List,
  "list-checks": ListChecks,
  "list-ordered": ListOrdered,
  "list-plus": ListPlus,
  "list-x": ListX,
  "lock": Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "mail-open": MailOpen,
  "map-pin": MapPin,
  "maximize-2": Maximize2,
  "minus": Minus,
  "monitor": Monitor,
  "monitor-off": MonitorOff,
  "moon": Moon,
  "navigation": Navigation,
  "octagon-alert": OctagonAlert,
  "party-popper": PartyPopper,
  "pen-line": PenLine,
  "plus": Plus,
  "qr-code": QrCode,
  "receipt-text": ReceiptText,
  "refresh-cw": RefreshCw,
  "repeat": Repeat,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  "scan-line": ScanLine,
  "search": Search,
  "send": Send,
  "settings": Settings,
  "share-2": Share2,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shirt": Shirt,
  "shopping-bag": ShoppingBag,
  "shuffle": Shuffle,
  "smartphone": Smartphone,
  "square-pen": SquarePen,
  "star": Star,
  "sticky-note": StickyNote,
  "store": Store,
  "sun": Sun,
  "tent": Tent,
  "ticket": Ticket,
  "ticket-check": TicketCheck,
  "ticket-percent": TicketPercent,
  "ticket-x": TicketX,
  "timer": Timer,
  "timer-off": TimerOff,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  "undo-2": Undo2,
  "unplug": Unplug,
  "upload": Upload,
  "user-minus": UserMinus,
  "user-pen": UserPen,
  "user-plus": UserPlus,
  "user-round": UserRound,
  "user-x": UserX,
  "users": Users,
  "wallet": Wallet,
  "wand-sparkles": WandSparkles,
  wifi: Wifi,
  "wifi-off": WifiOff,
  "x": X,
  "zap": Zap,
};
